getsentry/develop

src/docs/sdk/index.mdx
"/sdk/event-payloads/index" -> "/sdk/event-payloads/overview"
=> fix: Event Payload page link

src/docs/environment.mdx
- Remove subjective "how to reload shell" (let folks figure out their own edge cases)
- Add cold-folded zsh examples
- Simplify a few language bits
=> Add zsh examples to environment docs (and simplify shell)

gatsby-config.js, plugins/gatsby-plugin-include/__tests__/__snapshots__/index.js.snap, plugins/gatsby-plugin-include/__tests__/index.js, plugins/gatsby-plugin-include/index.js, plugins/gatsby-plugin-include/package.json
Adds a shorthand for mdx imports:
```markdown
import "./foo.mdx"
```
as a shorthand for
```markdown
import Foo from "./foo.mdx"
<Foo/>
```
=> feat: Bare import syntax for mdx includes

src/docs/services/devservices.mdx, src/docs/testing.mdx
Port the testing content from https://www.notion.so/sentry/The-Standard-Sentry-Developer-s-Handbook-49cb5382fa884f30876379267f8c553e#f5911a9a5a764ef59a90b67ffd9406b2 to this guide, with the goal of phasing out the notion page.
=> Update testing guide based on notion

src/docs/sdk/store.mdx
Turns out that in Relay and in Sentry we only supported `zlib+base64` (with header).
=> fix: Describe actual supported content-encoding for /store/

src/docs/feature-flags.mdx, src/docs/testing.mdx
Pull in the longer guide I've been maintaining in notion to this project. Instead of having multiple examples for toggling features in tests, I've linked to the examples in the testing chapter.
=> feat(features) Expand the feature flag docs

src/docs/services/metrics.mdx
Our doc builder folds consecutive codeblocks into one codeblock with tabs. This does not make a lot of sense here.
=> fix: Split up code samples

src/docs/environment.mdx
We now have to use `make setup-pyenv` when we are setting up our development environment. 
See more details with Josh's PR on why we do this: https://github.com/getsentry/sentry/pull/18906
Also took the time to add a `zsh` snippet ~and add a troubleshooting prompt for python version issues.~
Closes https://github.com/getsentry/develop/issues/51 as it deals with the main issue.
=> fix: use correct pyenv command

src/components/sidebar.js, src/docs/continuous-integration.mdx
* Add CI notes and troubleshooting sections over.
* Reorganize sidebar to have a 'development' section covering
development life-cycle type information.
* Group application feature docs in 'Application' formerly 'understand'.
=> feat: Move more development handbook content over

package.json
Not too keen on downloading another node version to develop, so bump node to match the version I already use for Sentry.
This doesn't break anything locally for me.
Right now, I don't know if this needs to be bumped elsewhere.
=> build: upgrade node to match node version in sentry (v10.16.3)

src/docs/environment.mdx
When setting up getsentry you need to run `make bootstrap` prior to  `make develop` you'll receive an error saying the getsentry database doesn't exist.
=> docs: Add missing make command

src/docs/serializers.mdx
The python snippets used both tabs and spaces which caused inconsistent indentation.
Defaulted to use 4 spaces.
Example:
=> Fix inconsistent tabs and spaces

src/docs/sdk/unified-api/tracing.mdx
The double sampling has happened accidentally both in JS and Python, and fixed in [getsentry/sentry-javascript#2600](https://github.com/getsentry/sentry-javascript/pull/2600/files#diff-377e14ef259b8bd726753063b8658e97) and https://github.com/getsentry/sentry-python/pull/732, respectively.
---
=> feat: Note about sample rates for tracing

src/docs/sdk/store.mdx
Single quotes don't get variables interpolated.
=> Fix quotes.

src/docs/environment.mdx, src/docs/sentry-vs-getsentry.mdx
@robinrendle Sorry, this is a bit late, but these are nonetheless the changes I said I would make.
Also, I changed instructions for getsentry to only use `make bootstrap` for 1st time setup because there is no reason for this part to be different than sentry setup which is also just `make bootstrap`. That actually doesn't currently work in getsentry, so I'm gonna make those changes: https://github.com/getsentry/getsentry/pull/4111. Which blocks this PR.
And, any opinions on automating virtualenv creation in `make bootstrap` since its a 1st time thing? That'd be some less manual steps.
=> ref: some devenv doc clarifications

src/docs/frontend/index.mdx
According to the outcome of one of our TSC meetings (https://www.notion.so/sentry/93d1ddb057af4a4db67c9b741c5ab495?v=e97ab611c4b54951a6ca3e10e13be16e&p=99c691667f724ad080cb958103a36d54), I am updating this handbook by adding a section on using the index file in a component folder.
This PR also adds best practices when naming a file.
=> feat(frontend): Add File naming/structure section

src/docs/sdk/event-payloads/index.mdx
Depending on platform, the logger is not always available/known. It has been an optional attribute in practice, document it as such.
=> fix: event.logger attribute is optional

src/docs/sdk/envelopes.mdx
This is a change to how we want to deal with this sdk meta data.
=> fix: sdk info is actually sdk

src/docs/sdk/envelopes.mdx
See https://github.com/getsentry/relay/pull/671
=> ref(envelope): Update size limits for envelopes and attachments

src/docs/environment.mdx
Per feedback from helping @cameronmcefee set up from scratch.
Mainly:
- direnv moved to after bootstrap to reduce confusion since we have it check for a bootstrapped environment
- PR to remove from sentry Brewfile so that it isn't installed in the beginning when `brew bundle` is run: https://github.com/getsentry/sentry/pull/20011
- added tip to manually source before bootstrap since prior steps involve reloading the shell
- bin/load-mocks is broken (has been for many months), so tip was removed (can be resurrected if someone fixes it lol)
=> ref: environment docs polish

src/docs/sdk/envelopes.mdx
Adds a note on the minimum onpremise version required to support envelopes.
---
=> feat(envelopes): Add a note on backwards compatibility

src/docs/environment/index.mdx
- adds `mock-subscription` to the getsentry setup docs and troubleshooting section since this is a common question
- updates to getsentry's Makefile are in [#4303](https://github.com/getsentry/getsentry/pull/4303), which adds `mock-subscription` to `make bootstrap` so it is run on initial setup, instead of only `make reset-db`
=> fix(docs): Add to getsentry troubleshooting

src/docs/sdk/event-payloads/properties/sampled.mdx, src/docs/sdk/event-payloads/span.mdx
This was never a proper part of the protocol as understood and implemented in Relay.
The JS SDKs used to send this as a side-effect of how it serialized the internal span representation into JSON.
=> fix: Remove span.sampled from API docs

src/components/sidebar.js
We used to point people to the homepage of on-premise, advocating for the nightly builds. With this patch, we point them to the latest release.
Rel: https://app.asana.com/0/1169344595888357/1190341230301201/f
/cc @PeloWriter
=> ref(onpremise): Point people to the latest release

src/docs/sdk/sessions.mdx
Still an open question:
* how should `start_session` behave with regards to ending the previous session. In case you have application-mode or request-mode.
=> docs: Clarify session modes and give SDK suggestions

src/docs/sdk/event-payloads/properties/status.mdx, src/docs/sdk/event-payloads/properties/transaction.mdx, src/docs/sdk/event-payloads/span.mdx
This was never a proper part of the protocol as understood and
implemented in Relay.
The transaction name is sent as a top-level field in the event payload,
it is not part of a span.
=> fix: Remove span.transaction from API docs

src/components/sidebar.js, src/docs/services/ports.mdx
Wanted this for a while, with obvious bias towards the services I work on:
* snuba devserver probably listens to more ports if ran outside of docker
* data-team has some services???
=> feat: Add list of used ports in sentry dev env

src/docs/onpremise/releases.mdx
This is a first pass for on-premise releases without any connection to the new document. We will be adding an on-premise homepage that links to this document.
See https://app.asana.com/0/1169344595888357/1190341230301205/f.
=> feat(onpremise): Add on-premise releases documentation

src/components/sidebar.js, src/docs/onpremise/index.mdx, src/docs/onpremise/releases.mdx
This converts the onpremise/basics page into a landing page for on-premise.
See https://app.asana.com/0/1169344595888357/1191462835804799/f
=> feat(onpremise): Add a landing page for on-premise

src/docs/services/ports.mdx
This updates and resolves the relay port conflict. See https://github.com/getsentry/sentry/pull/20668
=> ref(services): Update/resolve relay port conflict

src/docs/sdk/envelopes.mdx
The filename for attachment items is required, as the attachment can otherwise
not be persisted properly. This was enforced in the Minidump multipart upload
endpoint, but not when ingesting Envelopes.
There will be an additional fix in Relay to default the name if it is missing,
but it is required, regardless.
---
=> fix(envelopes): Require filename item headers

src/docs/environment/index.mdx
With moving to GHA, our wheels can only build on 10.15+, which means older systems (and Windows) need a Rust compiler.
=> feat(devenv): Describe Rust requirements

src/docs/sdk/unified-api/tracing.mdx
This came up in this PR and in Discord
https://github.com/getsentry/sentry-php/pull/1092
We should document to have this.
=> feat: Add from/to traceparent

package.json
We already require Yarn through Volta so replace all references to `npm` in `scripts` with `yarn`.
=> ref(scripts): Use yarn everywhere

src/docs/testing.mdx
Setting a timestamp helps prevent clock alignment problems, and add example of storing an event.
cc @Zylphrex
=> feat(test) Improve docs on saving events in tests

src/docs/sdk/event-payloads/message.mdx
Add info that Sentry accepts events where message.formatted is empty to support
legacy SDKs.
=> fix: Add info on Message.formatted

src/docs/sdk/unified-api/tracing.mdx
This PR adds docs about the new `tracesSampler` option for dynamic sampling. It also clarifies some of the text about the sampling decision in the `sentry-trace` header, and incorporates a number of formatting changes prettier felt the need to make.
The meaningful changes are all in the first commit: https://github.com/getsentry/develop/commit/36fd84d28e8062652a4848be32b4cb71fcbcd3d3.
=> feat(tracing): Add docs about `tracesSampler` option

src/docs/docs-components.mdx
We missed closing one of the code blocks.
=> fix(typos): Fix typo and off-by-one error on code samples

src/docs/docs/api.mdx
We've changed the location of where the SHA is put. So, update the docs.
=> fix(api-docs): Update sentry-docs SHA location

src/components/sidebar.js, src/docs/integrations/gitlab.mdx, src/docs/integrations/index.mdx
This PR adds GitLab setup instructions - however it's the same as installing GitLab on SaaS so I just followed the format for creating the app as we have for other local integrations and then link to the setup docs on SaaS.
=> feat(GitLab): Add on prem user docs

src/docs/config.mdx
The feature flag isnt useful, and you have to configure auth.allow-registration in order for it to work.
=> feat: Document the auth.allow-registration flag

src/docs/sdk/event-payloads/exception.mdx
Cleared up the wording a bit while fixing the glaring typo 😀
=> fix: Fix the wording on the `synthetic` flag

src/docs/docs/api.mdx
Now, we use Github Actions to automatically trigger new builds in sentry-docs when the OpenAPI changes.
This PR changes the docs to reflect this.
=> update(openapi): Manual steps replaced by Github Actions

src/docs/sdk/envelopes.mdx
The user facing wording of user report is now user feedback on Sentry. When implementing
user feedback on SDKs you have to impliclictly know that user feedback was once called user
report. Therefore UserReport is now renamed to User Feedback for the envelopes so devs can
find it quickly. Furthermore, information about the JSON of the envelope item is added.
=> feat(envelope): Change user report to user feedback

src/components/sidebar.tsx, src/docs/integrations/bitbucket.mdx, src/docs/integrations/index.mdx
Add instructions for how to use Bitbucket when running Sentry on prem.
=> feat(bitbucket) Add on prem user docs

src/docs/sdk/unified-api/tracing.mdx
This document says:
> To avoid confusion with the W3C `traceparent` header (to which our header is similar but not identical), we call it simply `sentry-trace`.
No version is being defined in the header.
To avoid further confusion, let's name the function that parses/creates `sentry-trace`:
`toSentryTrace` and `fromSentryTrace`.
=> call sentryTrace instead of Tracecontext

src/components/sidebar.tsx, src/docs/integrations/azuredevops.mdx, src/docs/integrations/index.mdx
Add instructions for installing Azure DevOps in an on prem instance of Sentry. Also alphabetize the sidebar and index page.
=> feat(azure devops): Add on prem user docs

src/docs/frontend/storybook.mdx
We have removed the GCS bucket where it was previously deployed and have migrated to Vercel.
=> feat: Update documentation about Storybook

src/docs/integrations/azuredevops.mdx, src/docs/integrations/bitbucket.mdx, src/docs/integrations/github.mdx, src/docs/integrations/slack/index.mdx
We use `{YOUR_DOMAIN}` in most of our integration docs, so, keep the rest of the integration docs consistent with that terminology.
Also, removing references to ngrok cause these docs can be used as on prem docs too (in addition to development docs), which shouldn't be on ngrok.
=> fix(integrations): Change URL prefix to be consistent across integrations

src/docs/sdk/unified-api/tracing.mdx
And move `fromSentryTrace` to TransactionContext as you can't continue individual spans.
=> Add continueFromHeaders/iterHeaders methods

src/docs/sdk/event-payloads/debugmeta.mdx, src/docs/sdk/event-payloads/stacktrace.mdx
This documents the protocol changes for WASM support.
Depends on https://github.com/getsentry/relay/pull/852
=> feat: Document WASM protocol extensions

src/docs/sdk/envelopes.mdx, src/docs/sdk/sessions.mdx
This is in line with https://github.com/getsentry/relay/pull/815 and https://github.com/getsentry/sentry-rust/pull/284
=> docs: Add aggregate sessions payload

src/components/sidebar.tsx, src/docs/self-hosted/geolocation.mdx, src/docs/self-hosted/index.mdx, src/docs/self-hosted/sso.mdx
Goes with https://github.com/getsentry/onpremise/pull/766.
Closes #220.
Don't merge until https://github.com/getsentry/onpremise/pull/766 is merged **and released**, hopefully will be in 20.12.0.
=> Add docs on geolocation

src/docs/sdk/event-payloads/index.mdx
Documents the previously internal error list on the event payload, which allows SDKs to attach general errors with handling an event. This list should not be used for annotating individual fields, as this will be done automatically during ingestion, or otherwise should be done via `_meta`.
=> feat(payload): Specify event errors

src/docs/sdk/features.mdx
Add more context on how to implement the user feedback API on user facing platforms.
Fixes GH-218
=> feat: Document the User Feedback API

src/docs/sdk/event-payloads/user.mdx
Pulls user interface attribute descriptions from `sentry-docs` and adds a section on when to use `{{auto}}` in IP addresses.
Ref https://github.com/getsentry/sentry-docs/issues/2821
Ref https://github.com/getsentry/sentry-docs/pull/2822
---
=> feat(payloads): Document {{auto}} for user IP addresses

src/docs/inclusion.mdx
Primarily this was to fix subject/verb agreement in the last paragraph, but I couldn't help smoothing a few other tiny language bumps along the way.
=> fix(typos): Tiny edits on inclusive language page

src/docs/environment/index.mdx
Python 3 does not require installing the `virtualenv` package since it is included
by default as a module.
=> environment: No need to install virtualenv

src/docs/sdk/envelopes.mdx
Specify that any valid MIME type can be used as a content type. Brought up in here https://github.com/getsentry/sentry-docs/pull/2826#issuecomment-755500370.
=> fix: Specify valid content types

src/docs/sdk/performance.mdx, vercel.json
In this PR we want to address some of the points of this issue https://github.com/getsentry/develop/issues/221
Goals:
* Better general guidelines for SDK developers to implement performance monitoring support
* FAQ section at the end with common questions that come up
* Links to source code of different SDKs to demonstrate how it was done so far
* Clearly communicate some differences (EventProcessor is called in JS but not in others SDKs necessarily).
=> SDK documentation for Performance Monitoring

src/docs/docs/api.mdx
We want to include steps on how to setup the local dev environment to update the API docs in `sentry-docs`.
=> feat(docs): Add local dev setup for API docs

src/docs/sdk/features.mdx
The link to transaction was broken. It is fixed now. I also changed the passive
voice to an active.
=> fix: AddToTransaction link to transaction

src/components/sidebar.tsx
Sidebar links are hardcoded, so when a page is moved (as happened in https://github.com/getsentry/develop/pull/240), the sidebar has to be updated by hand.
Fixes https://github.com/getsentry/develop/issues/252.
=> fix(SDKs): Update performance link in sidebar

src/docs/python-dependencies.mdx
Since Github does not call the "first comment" a "description".
=> Terminology change for where to place the tag

src/docs/sdk/event-payloads/contexts.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/1590.
=> Fix: context name not required when raw_description is given

src/docs/environment/index.mdx
I use the `fish` shell, so setting up the environment worked a little differently than for `bash` and `zsh`.
=> Environment: added instructions for fish shell

src/docs/sdk/event-payloads/exception.mdx
This adds `ns_error` to the mechanism protocol.
For more details see https://github.com/getsentry/sentry-cocoa/discussions/929
=> Added NSError to protocol

src/docs/environment/index.mdx
Running `brew cask upgrade chromedriver` outputs the following:
```
Error: Calling `brew cask upgrade` is disabled! Use brew upgrade [--cask] instead.
```
Ref: https://stackoverflow.com/questions/31968664/upgrade-all-the-casks-installed-via-homebrew-cask
https://github.com/Homebrew/discussions/discussions/340
=> fix: Use official cask upgrade command

src/docs/sdk/data-handling.mdx, src/docs/sdk/event-payloads/request.mdx
This addresses confusion on size limits and aligns them with the actual implementation in Relay.
See https://github.com/getsentry/sentry-docs/issues/3094
cc @PeloWriter
=> fix: Payload and request size limits

src/docs/environment/pycharm/index.mdx
Devserver's `--skip-daemons` flag has been removed and entirely replaced
by `--debug-server`. Update and simplify all associated instructions.
Delete or trim down tips that are no longer as relevant.
=> fix(docs): Update "Debugging with PyCharm"

src/docs/docs/api.mdx
Add some more information, steps, and tips to documenting an endpoint. These things would have helped me when I recently added some after not working on it for several months.
=> ref(api docs): Add guidance and tips to documenting an endpoint

src/docs/processing-tickets.mdx
This partially addresses https://github.com/getsentry/open.sentry.io/issues/1.
=> Account for external triagers

src/docs/python-dependencies.mdx
We're moving toward treating `sentry` as a requirement of `getsentry`,
thus, dependencies on `sentry` do not need to be defined on `getsentry` as well.
We also won't need to synchronize PRs on both repositories.
=> Python dependencies hard pinned in Sentry (no more getsentry)

src/docs/sdk/event-payloads/breadcrumbs.mdx
Fixes a link, removes an accidentally-duplicated paragraph, corrects a statement about multiple `breacrumbs` properties, and fixes a few small typos which jumped out at me in a quick skim.
=> fix(breadcrumbs): Fix link, do other minor cleanup

src/components/sidebar.tsx, src/docs/analytics.mdx
We should document how we can instrument our code with our current analytics infrastructure. 
I added docs on Big Query and Datadog with an implementation example.
=> feat(analytics): Add docs on analytics

src/docs/sdk/event-payloads/stacktrace.mdx
Was added with https://github.com/getsentry/relay/pull/981. Merge this once we deployed this.
=> feat: Add stack_start to stacktrace interface

src/docs/sdk/sessions.mdx
Remove experimental status, since we already rely on the documented/implemented behavior in several SDKs for "request mode" session reporting.
=> fix: Session Aggregates Payload experimental status

package.json, src/components/search.tsx, yarn.lock
Previously, when using the search, we'd query all indexes regardless of whether you were viewing them. This updates to only search the primary index (develop) until you opt to show all indexes.
=> Feat (search): Search only primary index by default

src/components/search.tsx
- When results for same site, show results + "show other sites" button
- When no results, automatically start showing results for other sites
- If no results for any site, show no-results view
- When the user clears the input, reset the state of the search bar
- Don't search single character queries
=> Feat: Update Search to better handle zero-hit results

src/docs/sdk/event-payloads/contexts.mdx
This PR proposed to add a `brightness` field to the OS context.
All major OSs (Windows, macOS, Linux (Ubuntu), Android, iOS) have implemented dark mode. 
Darkmode is a system wide option, thus I added this to the OS context.
I could imagine that it also makes sense as a field of the app.
=> Proposal: Darkmode field for OS context

src/docs/sdk/sessions.mdx
https://github.com/getsentry/develop/pull/323#issuecomment-842332513
=> Guidelines for sessions in SDKs

src/docs/sdk/event-payloads/contexts.mdx
This PR is a proposal to add a `current culture` context to Contexts. 
It contains various kinds of information around the culture which is in use.
Who is using this (at least these are the ones I'm aware of):
- https://github.com/getsentry/sentry-dotnet
- This Draft PR is also adapting to it: https://github.com/getsentry/sentry-dart/pull/452
Where this also might be useful:
- Android
- iOS
- Desktop Linux
- Windows
- macOS
- Browser (?)
Additional relevant properties not yet included:
- decimal seperator
- units (weight, length, money)
Why do I want to have this information?
When my software supports multiple cultures/locales and I'm
- Parsing strings into numbers
- Calculating with units
- Displaying dates
=> Proposal: Culture Context

src/docs/sdk/features.mdx
=> Document Expected Features for the HTTP client integrations

src/docs/docs/api.mdx
With the switch to GitHub issue forms (https://github.com/getsentry/sentry/pull/26898), these links have changed.
cf. https://github.com/getsentry/static-sites/pull/554 https://github.com/getsentry/sentry/pull/27153
=> Fix new issue links

src/docs/sdk/features.mdx
Add a comment to HTTP client integrations in expected SDK features to exclude
HTTP requests to Sentry.
=> feat: Exclude Sentry HTTP in client integrations

src/docs/sdk/features.mdx
Add an additional parameter to the HTTP Client Integrations breadcrumb.
The reason why is having a breadcrumb with more value, knowing the status code from an HTTP Request will help the use user to differentiate if the given request was "healthy" or errored. 
In addition, this is the current behavior from Sentry Angular (and by that, I'll assume the Javascript SDK also does the same)
* For reference, see the following discussion: https://github.com/getsentry/sentry-cocoa/issues/1197#issuecomment-877668159
* Sample event with status_code set: https://sentry.io/organizations/sentry-sdks/issues/2280281206/events/4cb980d3b4044b429ad876f9c9187a1e/?project=5428537
* Development documentation that contains the status_code for breadcrumbs: …
=> ref: add status code to SDK http client integrations

src/components/sidebar.tsx, src/docs/sdk/research/performance/index.mdx
Creating a space to summarize the evolution of the tracing SDK APIs and where we go next.
This is the first part. Will continue on follow up PRs for ease of reviewing.
=> Document tracing SDK API evolution

src/docs/self-hosted/geolocation.mdx, src/docs/self-hosted/index.mdx
Newer SDKs don't send IP addresses by default, which breaks geolocation. Let's warn people about this.
https://forum.sentry.io/t/re-geolocation-doesnt-work-on-default-sentry/14651
=> Add warning to Geolocation doc about PII

src/docs/sdk/research/performance/index.mdx
That's what we do instead of starting the document with an `<h1>` (`#` in markdown) because it makes the title available as metadata for the static site generation.
=> Use markdown front matter for page title

src/docs/sdk/research/performance/index.mdx
Follows up on #381.
Extracted from https://github.com/getsentry/develop/pull/382/files#r675710473.
Thanks @lobsterkatie!
=> Proof-reading edits to scope propagation issues

src/docs/self-hosted/troubleshooting.mdx
This PR adds a section to the Troubleshooting guide on dealing with Postgres disk space usage due to `nodestore` and what happens if Postgres fails to release disk space from deleted rows.
From https://github.com/getsentry/onpremise/issues/783#issuecomment-880448830
=> Add troubleshooting section on Postgres disk space

src/docs/sdk/performance.mdx
After discussion with the team, it was decided that `SpanContext` should be immutable.
See: https://github.com/getsentry/sentry-cocoa/issues/1254
=> ref(perf): Add note about immutable SpanContext

src/docs/self-hosted/index.mdx
I encountered this problem while upgrading. As fare as I understand the upgrade path `21.6.1` is the last version that still can migrate off `South`. See [21.6.1](https://github.com/getsentry/sentry/blob/21.6.1/src/sentry/runner/commands/upgrade.py) vs [21.6.2](https://github.com/getsentry/sentry/blob/21.6.2/src/sentry/runner/commands/upgrade.py). [e062636](https://github.com/getsentry/sentry/commit/e06263660e6ddf458a3c8c4d2014af5f14552a17) also mentions `21.6.1` as stopper in the changelog.
=> Specify 21.6.1 as stopper instead of 21.6.3

src/docs/sdk/features.mdx
In expected features, the breadcrumbs section doesn't mention which types of breadcrumbs. This is fixed now by adding a few examples.
=> feat: Add different types of breadcrumbs

src/components/sidebar.tsx, src/docs/self-hosted/custom-ca-roots.mdx, src/docs/self-hosted/index.mdx
Result of poking and prodding from getsentry/sentry#26851
Documentation for getsentry/onpremise#1015
=> docs(onpremise): Document adding custom CA roots

src/docs/sdk/research/performance/index.mdx
Follows up on #356 and #381.
Documents the current Sentry span ingestion model, compare the model to alternatives, lists and explains several identified issues and wraps up with a summary for all identified issues (scope propagation and ingestion model).
=> Document tracing issues related to ingestion model

src/components/sidebar.tsx, src/docs/self-hosted/index.mdx, src/docs/self-hosted/releases.mdx
This PR does 3 things:
1. Fix the hard-stops section in upgrading to indicate the need for `21.6.3`.
2. Consolidate 'Upgrading' sections in the main overview and 'Versions & Releases' page under the renamed 'Releases & Upgrading' page
3. Reorder sidebar items for importance and relevance.
Refs getsentry/onpremise#1062.
=> fix(self-hosted): Consolidate and fix upgrade docs

src/components/sidebar.tsx, src/docs/api/checklist.mdx, src/docs/api/concepts.mdx, src/docs/api/index.mdx, src/docs/api/public.mdx
This PR does the following:
It is currently nested under "Documentation Guide" and it's not easily findable.
This has been moved from our internal wiki to the develop site. This was discussed and agreed upon during the last backend TSC. Since what was presented in backend TSC:
1. I've removed which status codes we respond with cause it was simply listing out the HTTP spec
2. Have not added guidelines on error objects - this is still something we should do but I do not want to block these guidelines while we figure that out
3. Made the list numbered
This has also been moved from our internal wiki. I've added `collapse` to the guidelines.
Please click on the Vercel link to see what this will look like on production.
=> feat(api): Add API checklist and API concepts

src/components/sidebar.tsx, src/docs/sdk/trace-context.mdx
Rendered: https://develop-git-feat-trace-context.sentry.dev/sdk/trace-context/
=> feat(sdk): Describe trace contexts

src/docs/sdk/event-payloads/span.mdx
Add status to the example as it is one of the possible fields.
Reorder fields in some logical way for readability, most important and required fields first.
=> Add status to span payload and reorder fields logically

src/docs/sdk/performance/trace-context.mdx
This fixes two problems with the docs on how to handle third-party `tracestate` data:
- In the "joined by comma" example in the Tracestate Headers section, there shouldn't be a space between the entries. See https://www.w3.org/TR/trace-context/#combined-header-value.
- In the last snippet in that same section, with an example header containing both sentry and third-party data, the order needs to be reversed, since whatever key-value pair you're adding or modifying should end up the leftmost one. See https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field.
=> fix(tracing): Small fixes to tracestate docs about third-party data

src/docs/inclusion.mdx
This PR simplifies the instructions for setting your default `git init` branch name to use the `init.defaultBranch` config option that was introduced in Git 2.28 (released last year, around July 2020).
See https://github.blog/2020-07-27-highlights-from-git-2-28/#introducing-init-defaultbranch for GitHub's 27th July 2020 blog post on the topic.
I opted to add the wording "As of Git 2.28" to the docs, in case anyone's got a client over a year out of date, and since Git won't produce any error if it comes across a config option it doesn't know about. (So it would silently appear to succeed if the user's on an older version)
=> ref(general): Simplify inclusion.mdx "Git Branch Naming"

src/docs/sdk/performance/index.mdx
The `lastEventId` is often used for reporting a user feedback dialog or related use cases. We decided not to update `Hub.lastEventId` for transactions to keep that workflow working.
=> Don't set lastEventId for transactions

src/components/sidebar.tsx, src/docs/sdk/client-reports.mdx, src/docs/sdk/index.mdx, src/docs/sdk/rate-limiting.mdx
This adds a section to the documentation that covers the new client report envelope items.
Refs https://github.com/getsentry/relay/pull/1074
=> feat: Documentation for client reports

src/docs/sdk/performance/trace-context.mdx
The implementation guidelines for the trace context were a bit
misleading. On Java, for example, the first implementation only added the envelope
header for transactions bound to the scope.
This is fixed now by changing the wording a bit.
=> ref: Clarify Trace Context SDK Guidelines

src/docs/sdk/envelopes.mdx
* add a note regarding envelope header being required
* remove an example without envelope header
* fix title of one of the examples
=> docs(envelopes): Update envelope header requirement

src/docs/testing.mdx
It wasn't obvious that Kafka wasn't running in our generic backend tests.
=> add info about Kafka tests in CI

src/docs/services/queue.mdx
Adds link to https://docs.sentry.io/product/cli/
=> add link to sentry-cli docs

src/docs/environment/index.mdx
In this [Sentry PR][PR], we remove the Docker initialization code since it broke
few months ago.
[PR]: https://github.com/getsentry/sentry/pull/28352
=> fix(dev): Change info on how to start Docker

src/docs/sdk/unified-api/index.mdx
I'm no native speaker, but "it also setups all default integrations" felt wrong when I just read it in the docs. This PR replaces it with:
> it also sets up all default integrations
=> docs/unified-api: Fix wording issue

src/docs/sdk/data-handling.mdx
I assume https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization was meant, since `Authentication` does not seems to be a standard HTTP header.
=> docs/data-handling: Fix HTTP header name

src/components/sidebar.tsx, src/docs/frontend/index.mdx, src/docs/frontend/using-rtl.mdx
A follow-up to the discussion of the October 7th frontend TSC.
I kicked it off with tips around querying+assertions and pitfalls around that.
=> feat: Start react testing library guide

src/docs/database-migrations.mdx
This PR will add a code snippet to explain how to modify migrations to safely add defaults in new columns.
=> feat(docs): Add code snippet for safely using defaults in new columns

src/docs/continuous-integration.mdx, src/docs/feature-flags.mdx, src/docs/self-hosted/backup.mdx, src/docs/self-hosted/custom-ca-roots.mdx, src/docs/self-hosted/geolocation.mdx, src/docs/self-hosted/index.mdx, src/docs/self-hosted/releases.mdx, src/docs/self-hosted/sso.mdx, src/docs/self-hosted/support.mdx, src/docs/self-hosted/troubleshooting.mdx
https://github.com/getsentry/self-hosted/issues/796
=> Rename onpremise to self-hosted

src/docs/frontend/using-rtl.mdx
Add a new tip to the React Test Library doc, recommending using `userEvent` instead of `fireEvent` whenever possible.
=> ref(RTL): Add tip  with recommended library for testing user interactions

src/docs/self-hosted/index.mdx
Relates to https://github.com/getsentry/onpremise/pull/1113.
=> Add note regarding Dot Env custom file

src/docs/integrations/vercel.mdx
We made some changes to the Vercel integration a few weeks back (see https://github.com/getsentry/sentry/pull/26162). This needs an update to our develop docs so that on prem users can use the integration. So, here are the updates.
=> docs(vercel): Update Vercel develop instructions

src/components/sidebar.tsx, src/docs/sdk/event-payloads/properties/op.mdx, src/docs/sdk/performance/span-operations.mdx
Edit: Please note, the scope of this PR has changed since it's creation. After reading the PR description, please see: https://github.com/getsentry/develop/pull/452#issuecomment-983716185
This PR adds documentation around the span operations spec that we use.
Before reviewing, I would recommend reading through the `Introduction` of this document: [https://develop.sentry.dev/sdk/research/performance#introduction](https://develop.sentry.dev/sdk/research/performance#introduction)
`OpenTracing`, which we based our initial performance product off of, had a concept of operation name. We can see it being leveraged in this [early JS SDK PR](https://github.com/getsentry/sentry-javascript/pull/1918/files#diff-b7d385e8e3c69cd4ade2edd41436b21255dde1d851717dc5c22cc7623a911a37R61).
According to …
=> feat(perf): Document span operations spec

src/docs/sdk/event-payloads/contexts.mdx
The example of the language is actually a locale, instead, it should be a
language.
=> fix: Description of language of device context

src/docs/integrations/msteams/index.mdx
Microsoft has deprecated their App Studio in favor of a Developer Portal, and as such there is a new way to setup the MSTeams Sentry app.
=> ref(msteams): Update documentation to use Developer Portal

src/docs/integrations/gitlab.mdx
The GitLab app form has changed slightly, this PR updates the installation modal to reflect the new form.
sentry PR: https://github.com/getsentry/sentry/pull/31025
=> ref(gitlab): Update installation docs

src/docs/sdk/event-payloads/breadcrumbs.mdx, src/docs/sdk/event-payloads/exception.mdx, src/docs/sdk/event-payloads/threads.mdx
Sentry's ingestion server can deal with flat lists, and some SDKs have historically used that. To avoid confusion, document that possibility.
For implementation details, see
https://github.com/getsentry/relay/blob/4639455273ed8caccf5c11b929ef42d3a7ac6d61/relay-general/src/protocol/types.rs#L29
https://github.com/getsentry/relay/blob/4639455273ed8caccf5c11b929ef42d3a7ac6d61/relay-general/src/protocol/event.rs#L406-L430
Related: https://github.com/getsentry/sentry-go/pull/408
=> Document alternative format for Exception/Breadcrumb/Thread payload item

src/docs/sdk/rate-limiting.mdx
The description of a default rate limit is easy to miss since it's not declared
at response handling but rather the interpretation section. I'm moving this up
to the earlier list to make it more apparent.
=> ref(rate-limits): Promote 60s default rate limit

src/docs/environment/index.mdx
Running as is was causing `(eval):1: command not found: _direnv_hook()`
=> Fix direnv command in bash

src/docs/frontend/index.mdx
In the Frontend Handbook page in our developer docs, the code snippet for creating React components still says to use class based components, although we've moved onto using functional components instead. 
This PR changes the code snippet to use a functional component instead of class-based.
=> feat(docs): Use functional components instead of class based

src/docs/sdk/performance/index.mdx
The `span.finish()` and `transaction.finish()` methods can be given an optional `endTimestamp` value that allows for users to override the endTimestamp of a span/transaction. This is currently implemented in the JavaScript SDK
https://github.com/getsentry/sentry-javascript/blob/bb6f86502e1ea551fa503136a954844f77cca322/packages/tracing/src/span.ts#L232-L234
This PR updates the develop documentation to reflect this capability.
=> fix: Document `span.finish` optional endTimestamp arg

src/docs/api/public.mdx
add a few missing commas to fix example syntax.
=> fix(apidocs): correct syntax in example code

src/docs/api/public.mdx
with https://github.com/getsentry/sentry/pull/31711 we switched `public` from being a decorator to an attribute. the docs are updated accordingly.
=> chore(apidocs): update from decorator to attribute for public

src/components/sidebar.tsx, src/docs/environment/index.mdx
Requires getsentry/sentry#32497
=> feat: Disable relay by default in devservices

src/docs/sdk/envelopes.mdx, src/docs/sdk/rate-limiting.mdx
Add more hints that data categories and envelope item types are not the same.
=> fix: Data Category Confusion

src/docs/sdk/client-reports.mdx
Clarify that SDKs should primarily reduce needless communication.
Communicate that the requirements are recommendations that can
be adapted if needed.
=> fix: Client report sdk recommendations

src/docs/sdk/client-reports.mdx
`before_send` and `event_processor` should be in the list of discard reasons and not below the sentence
> Additionally the following discard reasons are reserved but there is no expectation
that SDKs send these under normal operation:
=> fix: Client report reasons

src/docs/sdk/client-reports.mdx
Document that there should be an option to turn on/off sending of client reports.
=> Document config option for sending client reports

src/docs/sdk/client-reports.mdx
Document that ignored exceptions (`ignore_errors` / `ignoredExceptionForTypes`) should be sent as reason: `event_processor`.
=> Document how to handle ignored exceptions

src/docs/environment/index.mdx
Our internal docs recommends us to increase docker memory limits:
https://www.notion.so/sentry/Dev-Environment-98b18b1e96e04f018e6e3d5d87f2889e#c5daa8c7cae647d4893348b6e5eaf97b
We should probably do the same on the environments we setup for developing sentry.
=> Add a blurb about increasing memory for docker

src/docs/sdk/client-reports.mdx
=> fix: Document min Sentry version for client reports

src/docs/sdk/sessions.mdx
For filter order and more info please see https://github.com/getsentry/develop/issues/537 and https://github.com/getsentry/sentry-java/issues/1916
Do we also want to document order of the filtering mechanisms? If so do we go with the python implementation order as a template?
=> Document session update for dropped events

src/docs/config.mdx
see: https://github.blog/changelog/2022-04-25-git-io-deprecation/
Committed via https://github.com/asottile/all-repos
----
By submitting this pull request, I confirm that Sentry can use, modify, copy, and redistribute this contribution, under Sentry's choice of terms.
=> fix: replace git.io links with redirect targets

src/docs/integrations/jira-server.mdx
Update the link here to the correct one so that it actually goes to the intended anchor - it was redirecting to https://docs.sentry.io/product/integrations/issue-tracking/jira/
=> fix(Jira Server): Update docs link

src/docs/python-dependencies.mdx
We no longer need devs to manually police license compliance because this is automated now.
=> Drop manual license guidance

src/docs/sdk/event-payloads/properties/measurements.mdx
Links to Relay's canonical `MetricUnit` documentation and updates the notice on custom units. Custom units are in fact supported in ingestion, but SDKs are encouraged not to expose them for the time being where possible. Also, there's now a range of information and fraction units in addition to durations.
This paragraph deliberately doesn't give SDK implementation advice since this document - like all payload docs - are more likely to be consumed by end users.
See https://github.com/getsentry/relay/pull/1256
=> ref(measurements): Link to Relay MetricUnit and update wording [INGEST-1131]

src/docs/integrations/jira/index.mdx, src/docs/integrations/slack/index.mdx
Update the Slack and Jira docs a bit to fix some links and clean up the page as I recently went through the setup process and noticed some things that could be improved. 
Honestly all of these pages could use some love, formatting, and standardization, but right now I just want correctness.
=> ref(integrations): Update integration docs

src/docs/config.mdx, src/docs/integrations/github.mdx, src/docs/self-hosted/sso.mdx
- Fix bad documentation in configuration page
- Add button to auto-generate GitHub app in GitHub Integration page
- Improve auto-generated GitHub app name in GitHub SSO
Closes : https://github.com/getsentry/self-hosted/issues/1486
=> Improve GitHub Integration configuration docs

src/docs/api/public.mdx
API docs are no longer built automatically by CI, updating the steps with the manual process
=> Update the build process

src/docs/api/public.mdx
- Based on feedback [here](https://github.com/getsentry/sentry-docs/pull/5115) include a local argument
=> fix: Add local argument

src/docs/sdk/features.mdx
There is an error in the docs:
This fixes the issue
=> Fix doc coding error

src/docs/api/public.mdx
https://github.com/getsentry/sentry-api-schema/pull/42
https://github.com/getsentry/sentry-api-schema/pull/43
https://github.com/getsentry/sentry-api-schema/pull/44
https://github.com/getsentry/sentry-docs/pull/5152
https://github.com/getsentry/sentry-docs/pull/5153
https://github.com/getsentry/sentry-docs/pull/5154
https://github.com/getsentry/sentry-docs/pull/5155
https://github.com/getsentry/sentry-docs/pull/5156
https://github.com/getsentry/sentry-docs/pull/5158
=> Document additional automation of API docs build

src/docs/self-hosted/support.mdx
The forum is in read only mode. Therefore users should be sent to GitHub Discussions instead.
It looks like https://github.com/getsentry/develop/blob/c36c3ad4a58b6a4fab7d3c3ef07b4030f10572cc/src/components/sidebar.tsx#L298 might need to change too - but I'm not sure if that should be to the same place?
=> Switch Forum link to GitHub discussions

src/docs/self-hosted/index.mdx
Here's the documentation to go with https://github.com/getsentry/self-hosted/pull/1543. I pulled it from https://github.com/getsentry/self-hosted/commit/ee2be4623417f155da35baccd426bc62627d37ca and edited it somewhat.
cc: @goganchic @BYK @aminvakil
=> Document self-hosted installation behind a proxy

src/docs/integrations/vercel.mdx
Vercel recently introduced [API Scopes](https://vercel.com/changelog/enhanced-security-with-new-api-scopes-for-integrations) for integrations on their marketplace, meaning Self-Hosted users will need instructions on which scopes to set up when they create their own apps.
=> fix(docs): Add new API Scopes for configuring Vercel Integration

src/docs/sdk/performance/dynamic-sampling-context.mdx
This PR adds a condition to including the `user_id` field in the dynamic sampling context (DSC) that is sent via the `trace` envelope header to relay or propagated via the `baggage` Http header in outgoing requests. 
As discussed in TSC and in Slack, adding `user_id` to the DSC raises a PII concern because many SDKs currently propagate the DSC via `baggage` in all outgoing Http requests. This means, that PII could be sent to third parties. To avoid this, the decision was made to only include the `user_id` if the `send-default-pii` init option was set to `true`.
It's important to note that another way of addressing issues like this one is in discussion, which is making the `tracingOrigins` option part of every SDK. With this option, users can clearly specify where tracing data should be …
=> ref(DSC): Only include `user_id` in DSC if the `send-default-pii` option is enabled

src/docs/sdk/event-payloads/properties/transaction_info.mdx, src/docs/sdk/event-payloads/transaction.mdx, src/docs/sdk/performance/index.mdx
Add a `source` label to every transaction that indicates how the transaction name was generated, as decided in https://www.notion.so/sentry/Annotating-Transaction-Names-a08a05ff97b348b0903de03a17baa731.
Rendered version is [here](https://develop-git-feat-transaction-source.sentry.dev/sdk/event-payloads/properties/transaction_info/) and will be included on the "Transaction Type" page.
=> feat(transactions): Add transaction_info.source [INGEST-1427]

src/docs/frontend/development-server.mdx
A developer may use the IPv4 URL from webpack's output and believe this did not work.
=> docs: Warn users against using an IP value

src/docs/sdk/performance/dynamic-sampling-context.mdx
Resolves https://github.com/getsentry/develop/issues/634
=> Add transaction back to DSC specification

src/docs/sdk/overview.mdx
The `sentry_client` value, part of the sentry authentication header or query params helps ingestion detect clients even in cases where the payload cannot contain an SDK identifier. It's therefore recommended -- while not strictly required -- to send this from all official SDKs.
=> ref(sdk): Mark sentry_client as recommended

src/docs/self-hosted/index.mdx
necessary code changes: https://github.com/getsentry/self-hosted/pull/1560
=> Improve self-hosted docs about installation behind the proxy

src/docs/database-migrations.mdx
Short addition specifying that the developer must also add to the __init__.py file when creating a new model, or it will not be recognized in testing. Multiple people have run into this issue recently.
=> Update database-migrations documentation

src/docs/sdk/performance/dynamic-sampling-context.mdx, src/docs/sdk/performance/index.mdx
This PR adds the spec for the new `tracePropagationTargets` SDK option. It is the result of the discussions we had about  giving users the ability to control where trace data is being propagated to (see [DACI Control Sending Trace Data](https://www.notion.so/sentry/DACI-Control-Sending-Trace-Data-63fd04ea885443ee99514c15a1e91499)).
resolves: #636
=> Add spec for tracePropagationTargets SDK Option

src/docs/integrations/slack/index.mdx
If this step is not taken, the installation of the Slack App will complain that the redirect URI points to http://localhost:8000.
=> Note on using Ngrok for local dev and installing Slack App

src/docs/docs/index.mdx
I always forget all of the places where docs guidelines live. This links two of them for better discoverability.
=> chore(docs): Add link to docs contribution guidelines

src/docs/sdk/event-payloads/contexts.mdx
Currently the `device` context has properties for the device memory usage but it can be useful to know how much memory an app was using when an event or transaction was captured. 
Open to better naming than `memory_used` 🤔
Related issues:
https://github.com/getsentry/sentry-cocoa/issues/999
=> Add `app_memory` to `app` context

src/docs/sdk/event-payloads/properties/transaction_info.mdx
`unknown` should only be set by Relay, as a value for SDKs that do not send the `source` attribute.
=> Discourage use of transaction source unknown

src/docs/sdk/basics.mdx, src/docs/sdk/data-handling.mdx, src/docs/sdk/features.mdx, src/docs/sdk/index.mdx, src/docs/sdk/overview.mdx, src/docs/sdk/philosophy.mdx, src/docs/sdk/rate-limiting.mdx, src/docs/sdk/signal-handlers.mdx, src/docs/sdk/store.mdx
* Being more explicit about our SDK guidelines for handling sensitive data
* Point out that changes to Relay have to happen to influence server side PII stripping
* Add to Philosophy
* Reorder pages to become a more sequential flow for learning
=> expand data handling

src/components/sidebar.tsx, src/docs/self-hosted/support.mdx, src/docs/self-hosted/troubleshooting.mdx
Part of https://github.com/getsentry/team-ospo/issues/27.
=> Repoint from forum to Github

src/docs/sdk/performance/dynamic-sampling-context.mdx
Link to https://docs.sentry.io/product/data-management-settings/server-side-sampling/getting-started/#current-limitations, rather than maintain a list in 2 places. Also add clarifying docs around what it means to be a fully featured DS SDK.
=> Update DS SDKs list to link to product docs

src/docs/sdk/performance/index.mdx
As not to confuse non JS devs who don't know that `/` is just a short hand syntax to create a regex in JS.
=> Remove delimiters from default regex for `tracePropagationTargets`

src/docs/sdk/performance/dynamic-sampling-context.mdx
Explains reasoning behind Java Impl with explicit param and mentions alternative approach with util function (as Dart uses).
=> Provide examples on toBaggageHeader

src/docs/sdk/performance/index.mdx
Point out that string literals don't have to be full matches.
=> fix: Clarify contains for tracePropagationTargets

src/docs/sdk/performance/span-operations.mdx
https://www.notion.so/sentry/Set-up-an-audit-for-SDK-consistency-for-span-operations-to-enable-performance-issues-addf02a8fa234dda8acf48d4ff9b8efb?d=b852bdd1e9914d2ca74c1052296081f3#d04af01302604881999b1bd29c837b1f
This PR attempts to align our span operations based on an audit we've taken on in the past 2 weeks. The reason we are trying to align our span operations is because they are required to generate consistent performance issues: https://github.com/getsentry/sentry/discussions/37083
In addition, to this PR, we've collected a list of span operations we'll need to update across the different SDKs: https://github.com/getsentry/develop/issues/693#issuecomment-1259423033
=> Update Span Operations for Audit

src/docs/sdk/performance/span-operations.mdx
The Angular SDK adds a few spans when using [component tracking](https://docs.sentry.io/platforms/javascript/guides/angular/components/tracehelpers/) features as well as when the [Angular routing instrumentation](https://docs.sentry.io/platforms/javascript/guides/angular/components/tracehelpers/) is used.
This PR adds these span operations to the JS Frameworks table, analogously to the span ops of our other Framework SDKs.
Open question: In [the docs (last code example on this page)](https://docs.sentry.io/platforms/javascript/guides/angular/components/tracehelpers/), we give an example on how to add custom spans to the Angular bootstrapping process. The span op we suggest for this span is `ui.angular.bootstrap`. Do we want to mention this in the dev spec? I didn't yet add it because …
=> ref: Add Angular SDK span ops

package.json, src/docs/sdk/event-payloads/user.mdx, yarn.lock
Document https://develop.sentry.dev/sdk/event-payloads/types/#geo
> Error: Node.js Version "12.x" is discontinued and must be upgraded. Please set Node.js Version to 16.x in your Project Settings to use Node.js 16.
=> Document geo location

.github/workflows/test.yml
this saves about ~30 seconds from the build time by caching yarn packages
=> ref: use sentry's setup-volta for better caching

src/docs/sdk/features.mdx
Add start-up crashes to expected features.
Related to https://github.com/getsentry/team-mobile/issues/12
=> feat: Start-up crashes

src/docs/sdk/performance/opentelemetry.mdx
We need to read from a map instead from scope in case we mistakenly create the wrong parent-child relationship.
=> Update otel algo to read map

src/docs/self-hosted/index.mdx
Adds some info on the self-hosted beacon from old docs that seem to no longer exist
=> Add info on self-hosted beacon

src/docs/sdk/performance/opentelemetry.mdx
Small update to the otel specs. Otel span attributes should be mapped to sentry span data, as attributes can be arbitrary - so mapping them to tags (which have to be strings) is tricky.
=> Update otel specs for span attribute mapping

src/docs/sdk/performance/opentelemetry.mdx
As `kind` is actually an integer, it does not make sense to map it to a tag, which has to be a string.
=> Otel `kind` should be mapped to `data`

src/docs/sdk/performance/opentelemetry.mdx
Fixes https://github.com/getsentry/develop/issues/733
Example implementation (with me misspelling propagator everywhere): https://github.com/getsentry/sentry-javascript/pull/6095
=> feat(otel): Add spec for SentryPropagator

src/docs/sdk/performance/opentelemetry.mdx
This one example was written in go, I think it makes sense for all examples to be written in the same language for consistency. Since I've implemented the same logic in TS in the meanwhile, we can update this here as well.
=> feat(otel): Make status mapping example use TS for consistency

src/docs/grouping.mdx
Noticed a few spelling mistakes while reviewing the grouping documentation
=> Fix some typos in grouping documentation

src/docs/sdk/performance/opentelemetry.mdx
This was accidentally used inconsistently.
=> fix(otel): Fix typo `instrumentor` to `instrumenter`

src/docs/self-hosted/troubleshooting.mdx
1. Warns users of potential data loss as highlighted [here](https://github.com/getsentry/self-hosted/issues/478#issuecomment-765037960) for kafka recovery
2. Add [solution](https://github.com/getsentry/self-hosted/issues/1690) contributed by user @gabn88
=> Add another solution to kafka error troubleshooting

src/docs/sdk/performance/index.mdx
It is called optionS and not option.
=> Fixed wrong HTTP OPTIONS spelling

src/docs/environment/index.mdx
Made the setup guide less confusing. 
I was setting up the development environment right now and in parallel changed all the passages in the guide that confused me.
I also made a small related change in `sentry`: https://github.com/getsentry/sentry/pull/41500
=> Update to development environment setup guide

src/components/sidebar.tsx, src/docs/sdk/performance/ui-event-transactions.mdx
Add specification for UI event transactions with Gherkin syntax.
Fixes GH-647
=> Add UI event transactions

src/docs/continuous-integration.mdx
I had to have all of this explained to me during onboarding, and then it immediately changed anyway, so I figure others might benefit. The [corresponding Notion document](https://www.notion.so/sentry/Deploying-Code-a39bd647e4e04f7a99cb30068feaed96) is stale.
- Update deployment instructions
- Clarify rollback instructions
=> docs(ci): Clarify deployment instructions

src/docs/sdk/event-payloads/contexts.mdx, src/docs/sdk/event-payloads/threads.mdx
Relevant rendered parts:
https://develop-git-feat-app-in-foreground-and-threading.sentry.dev/sdk/event-payloads/contexts/#app-context
https://develop-git-feat-app-in-foreground-and-threading.sentry.dev/sdk/event-payloads/threads/
Adds `in_foreground` to the App Context event payload, as well as `main` to the Thread Context. 
As these are all similar but not the same and given that we already have some thread flags this PR tries to clear up their meanings and make their purpose hopefully more understandable.
@marandaneto I'm adding you as an early reviewer as I suspect you have some strong opinions about this 😊 
Related mobile issue: https://github.com/getsentry/team-mobile/issues/36
=> feat: app.in_foreground and thread.main context flags

src/docs/sdk/performance/span-operations.mdx
We are going to add a ttid (time to initial display) span to the automatic activity transactions.
The use case is mainly for mobile developers.
The current activity transaction duration is not reliable to have an understanding of how much time it took to actually load an activity, due to possible other spans added during the transaction.
=> add ui.ttid to span operations

src/docs/sdk/performance/index.mdx
Add missing docs for this feature and clarify which span to return depending on global mode.
=> feat: Docs for Sentry.span

package.json
This is not a public package
This matches what sentry's package.json looks like
=> meta: Fix package.json to supress license warnings

src/docs/frontend/upgrade-policies.mdx
Cleans up a few stray things:
- `eg,` should be `e.g.` to match our docs (and most style guides)
- remove some stray characters, words, and phrases
- fix a few typos
=> chore(frontend): Tidy up upgrade policies doc

src/docs/config.mdx
Updates links from https://develop.sentry.dev/config/#logging to log levels at Python docs with Python 3-based ones.
cf. https://www.python.org/doc/sunset-python-2/
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
=> Use Python 3 docs for log level references

src/components/sidebar.tsx, src/docs/feature-flags.mdx, src/docs/options.mdx
There's appetite for updated `options` documentation. There's a smorgasbord of documents about `options` in Notion, but a lot of them are stale and/or confusing. This adds a dedicated `options` page, and adds it to the sidebar.
=> docs(application): Add options documentation

src/docs/sdk/performance/index.mdx
Looks like the `traceOptionsRequests` section was moved inside the `tracePropagationTargets` section. This moves it after `tracePropagationTargets`.
=> Move traceOptionsRequests section

src/docs/sdk/data-handling.mdx
In [RFC-0038](https://github.com/getsentry/rfcs/blob/main/text/0038-scrubbing-sensitive-data.md) we decided to implement better data scrubbing of sensitive data.
This is now the specification that all SDKs and Relay can implement to have better data scrubbing.
=> Specification: Better scrubbing of sensitive data

src/docs/sdk/performance/opentelemetry.mdx
As per: https://github.com/getsentry/sentry-javascript/pull/6724
Since the SENTRY_SPAN_PROCESSOR_MAP can be empty due to the transaction/span already finishing after the event processor was triggered (due to async event processors), we instead rely only on the OpenTelemetry context to determine the active span.
The product uses trace_id and span_id to associate errors to transactions, so that's what we've kept.
=> ref(otel): Update event processor to not use span map

src/docs/sdk/data-handling.mdx
Clarify that authority is replaced regardless of `sendDefaultPii` and it should be replaced with a placeholder instead of being omitted.
=> Clarify authority handling in URL

src/docs/options.mdx
This used to be a problem, but it no longer is. From https://github.com/getsentry/sentry/pull/43335#discussion_r1073800593
=> Don't discourage declaring and using options immediately

src/docs/sdk/features.mdx
Currently the PHP, Python, Ruby and NodeJS SDKs support local variables, but they all use inconsistent names for the option that gates this functionality.
- Ruby: [`capture_exception_frame_locals`](https://docs.sentry.io/platforms/ruby/configuration/options)
- Python: [`with_locals`](https://docs.sentry.io/platforms/python/configuration/options/#with-locals)
- PHP no option
- NodeJS [`_experiments.includeStackLocals`](https://docs.sentry.io/platforms/node/configuration/options/#_experiments.include-stack-locals)
I propose we rename this to `includeLocalVariables` / `include_local_variables`, unify these across the SDKs and add them when we get time
We also should decide if `sendDefaultPii` should have an affect on this.
cc @timfish
=> feat(unified-api): Define `includeLocalVariables` option

src/docs/sdk/event-payloads/sdk.mdx
This change adds the `source` field to the SDK interface that is part of the event payload.
We can use this source field to list the installation source of the SDK. For most cases this will be a package repository like `npm` or `pypi`, but it can also be things like `cdn`.
Current uses cases:
Browser Web:
- `npm`
- `cdn`
- `loader`
Apple:
- `spm`
- `carthage`
- `cocoapods`
=> feat(event): Add source to SDK payload

src/docs/environment/index.mdx
This PR documents how to enable the metrics ingestion pipeline, as discussed in slack with @untitaker.
=> docs: Add note how to enable metrics ingestion pipeline [TET-646]

src/docs/sdk/event-payloads/span.mdx, src/docs/sdk/performance/span-data-conventions.mdx
Fixes https://github.com/getsentry/develop/issues/816
I would like us to start tracking how we are setting/using keys and values on the span data field. Ideally we move toward using more of [OpenTelemetry's OOO semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/24de67b3827a4e3ab2515cd8ab62d5bcf837c586/specification/trace/semantic_conventions/README.md) for this, but add our own values as appropriate.
This is important, as we should make sure our spans behave consistently across different sdks and platforms. In addition, it helps us make sure that changing fields in the SDK won't break product usage.
We can also then look to use OpenTelemetry's span attributes for some of Sentry's generated spans. For example, we currently store the `url` as a string …
=> feat(perf): Add span data conventions

src/docs/sdk/performance/index.mdx
This PR is a proposal to resolve the discussion in https://github.com/getsentry/develop/issues/769. So that we may have a simpler option for turning performance and tracing on in Sentry SDKs.
Preview changes: [SDK Performance](https://develop-git-smeubank-enableperformance.sentry.dev/sdk/performance/)
=> Add enableTracing option

src/docs/sdk/client-reports.mdx
See https://github.com/getsentry/snuba/pull/3694
Note that there may be existing SDK usages that could leverage these new categories, eg. https://github.com/getsentry/sentry-python/blob/1268e2a9df1fe1fe2d7fc761d4330a5055db0e8e/sentry_sdk/transport.py#L253-L260
=> feat: Add client_report discard reasons `send_error` & `internal_sdk_error`

src/docs/sdk/event-payloads/sdk.mdx
This addresses the `sdk.name` and allows us to find out, for example: 
1. Events from React Native customers
2. Events from the Cocoa SDK (regardless of hybrid SDK that bundled it)
3. By looking at an event know exactly what SDK that is: It's cocoa version X but it was part of the Unity SDK
More importantly, this is simple, solves an actual problem we have right now. 
And we use this already on Unreal and Unity. Works as intended.
=> sdk.name for hybrid sdks

src/docs/sdk/event-payloads/contexts.mdx
- Reformat examples in the "Event Payloads / Contexts Interface" for better readability
- Added the "Cloud Resource Context" at the bottom of the page:
OLD Version:
https://develop.sentry.dev/sdk/event-payloads/contexts/
NEW Version: (Cloud Resource Context at the bottom)
https://develop-git-antonpirker-event-payload-cloud-context.sentry.dev/sdk/event-payloads/contexts/
=> New: Event payload Cloud Resource Context

src/docs/sdk/performance/opentelemetry.mdx
ref https://github.com/getsentry/team-webplatform-meta/issues/31
In OpenTelemetry, spans can have [exception events](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/exceptions/).
This spec defines how to create Sentry errors from these exception events and send them to Sentry.
=> feat(otel): Add spec for converting otel exceptions to sentry errors

src/docs/sdk/performance/opentelemetry.mdx
In #837 we introduced capturing otel error events.
In this quick change, we add the otel context to these captured error events, which allows us to identify that they were generated from an otel sdk in the product.
=> feat(otel): Add otel context to errors

src/docs/sdk/event-payloads/contexts.mdx
Removed saving the availability zone in different variables depending on the cloud provider. This changes makes everything easier.
=> Removed special case for GCP, because everything is

src/docs/sdk/event-payloads/contexts.mdx, src/docs/sdk/event-payloads/properties/contexts_trace.mdx, src/docs/sdk/event-payloads/properties/measurements.mdx, src/docs/sdk/event-payloads/properties/transaction_info.mdx, src/docs/sdk/event-payloads/transaction.mdx
- Moves "Trace Context" documentation form "Transaction Type" paget to "Contexts Interface" page. 
- Also cleaned up the "Transaction Type" page a bit.
=> Move "Trace Context" documentation

src/docs/environment/index.mdx
This adds a troubleshooting entry to the dev env setup docs, explaining that a connection error when running the dev server may be because devservices haven't yet been started.
Note: When DEVINFRA-30 is addressed, this will likely need to be modified or possibly even deleted.
=> chore(dev env): Add troubleshooting entry for devservices being down

src/docs/self-hosted/troubleshooting.mdx
For self-hosted, users may experience unhealthy containers from time to time which can usually be fixed by bringing the containers down and back up again
=> Add tip for resolving unhealthy containers

src/docs/sdk/performance/ui-event-transactions.mdx
Based on the discussion [here](https://github.com/getsentry/sentry-javascript/pull/7236):
- https://github.com/getsentry/sentry-javascript/pull/7236
I think we should update the develop docs and open issues for SDKs that already implemented the current scenarios to update it.
=> Update UI Event Transaction the same event same ui element scenario

src/components/sidebar.tsx, src/docs/rust.mdx
Document Rust best practices at Sentry.
Note: This is an updated version of https://www.notion.so/sentry/HOWTO-Code-Rust-at-Sentry-7b35f165b10b4492bb95ebe1471a9ada.
The PR serves as a starting point to discuss which guidelines we want to keep and which ones we want to add.
=> doc: Rust development

src/docs/rust.mdx
Move public re-exports (`pub use`) to the group of external and workspace
dependencies. This makes it easier to auto-format imports with tooling, as this
is how `cargo fmt` would format imports with available options.
---
=> feat(rust): Tweak imports for tooling

src/docs/sdk/data-handling.mdx
According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie the header is called `Cookie`.
=> Change `Cookies` to `Cookie` header

src/docs/feature-flags/index.mdx
updates docs for new feature flag manager signature added in https://github.com/getsentry/sentry/pull/46004
=> ref(features): update signatures to use enum in docs

src/docs/config.mdx
Along with https://github.com/getsentry/sentry/pull/46149, this attempts to clarify some points which weren't obvious to me as I was learning about our logging setup.
=> fix(config docs): Clarify description of default loggers

src/components/sidebar.tsx, src/docs/sdk/event-payloads/contexts.mdx, src/docs/sdk/event-payloads/span.mdx, src/docs/sdk/performance/trace-and-span-origin.mdx, src/docs/sdk/performance/trace-origin.mdx
Add docs for trace origin being used for trace context and spans. Trace origin indicates what created a trace or a span.
Every SDK will benefit from trace origin. Therefore, I tagged also @getsentry/team-web-sdk-backend and @getsentry/team-web-sdk-frontend.
Related [RFC](https://github.com/getsentry/rfcs/pull/73)
[Visit docs preview](https://develop-git-feat-trace-and-span-origin.sentry.dev/sdk/performance/trace-origin/)
=> Add trace origin

src/docs/sdk/event-payloads/stacktrace.mdx
Follows up on:
* https://github.com/getsentry/rfcs/pull/74
* https://github.com/getsentry/symbolicator/pull/1103
=> feat: add source_link to stack trace frame

src/docs/sdk/performance/trace-origin.mdx
Dots are allowed for trace origins.
Came up when opening PR to Relay https://github.com/getsentry/relay/pull/1984.
=> fix: Add dots to allowed chars for trace origins

src/docs/integrations/jira/index.mdx
This clarifies and expands upon the instructions for installing our Jira integration in the following ways:
- Explain that the Atlassian cloud instance is development-specific.
- Add section about installing ngrok, for folks developing locally.
- Clarify that the domain to use for the descriptor is the sentry domain, not the jira domain.
Note that the ngrok section is incomplete, insofar as it doesn't mention any of the changes you need to make to `sentry.conf.py`, but really that should probably go on its own page, which will have to be a separate PR. For the moment, the info is available in Notion.
Ref: WOR-2912
=> ref(integrations): Update instructions for installing Jira integration

src/docs/feature-flags/index.mdx
Fix the image path for all the images on the Flagr docs, plus put hover text where it is supposed to be.
=> ref(feature flags): Fix broken Flagr images and hover text

src/docs/sdk/features.mdx
With improved server side sampling Sentry attempts to already remove some transactions which do not provide value to the user. However this is a known case for many users for a long time. There is the traces sampler function, but the UX for this is bulky when you have a simple use case.
**Use case:** There transcations and errors which a users never wants sent to sentry, to appear in a feed or count against their quota.
**Proposal:** provide simple options which is a list of errors/exceptions and transactions, respectively, which the SDK will then always discard and never send to Sentry
**Preview:** [Event Sampling 
](https://develop-git-smeubank-define-ignore-options.sentry.dev/sdk/features/#event-sampling)
Similar implementations:
https://github.com/getsentry/sentry-php/pull/1503
JS …
=> Define ignore_errors & ignore_transactions

src/components/sidebar.tsx, src/docs/sdk/performance/time-to-initial-full-display.mdx
This PR adds instructions on what Time To Initial Display and Time To Full Display spans are and how to set them up
=> feat: add Time To Initial Display and Time To Full Display spans

src/docs/environment/index.mdx
Code block for ingest settings used `shell` and was therefore highlighted incorrectly - this block is actually Python code (goes into ~/.sentry/sentry.conf.py).
=> Fix programming language for sentry.conf.py block

src/docs/sdk/performance/trace-origin.mdx
The SDKs should set this trace origin automatically. It is not expected to be set manually by users.
=> Clarify SDKs set trace origin automatically

src/docs/sdk/performance/span-data-conventions.mdx
ref https://github.com/getsentry/team-webplatform-meta/issues/60
=> feat: Add span data for `db.system` and `cache.hit`

src/docs/sdk/performance/trace-origin.mdx
Add an example for manual trace origins having a category and an integration name.
=> Clarify manual trace origins

src/docs/sdk/performance/trace-origin.mdx
Remove dots from allowed chars for the parts of trace origins, so we can split up the trace origin into it's original parts.
=> Remove dots from trace origin allowed chars

src/docs/workflow.mdx
This adds a few notes about the way we typecheck Python files, based on various questions I've had and/or snags I've run into while onboarding to our Python codebase (and Python typing in general).
Note to reviewers: I'm not an expert here. Would be great to have someone who knows this stuff well check the veracity of this info. Also feel free to suggest any points I may have missed.
=> feat(workflow): Add section on Python typechecking

src/docs/self-hosted/troubleshooting.mdx
Replaces all `docker-compose` references to `docker compose`. Also adds a few forgotton `--rm` flags after `docker compose run` in Postgres section.
Further note: it might be better to convert these step-by-step guides into bash scripts for easy use.
=> Migrate self-hosted troubleshooting to compose v2

src/docs/sdk/performance/dynamic-sampling-context.mdx
Relates to: https://github.com/getsentry/team-webplatform-meta/issues/45
=> Send DSC on all envelopes

src/docs/integrations/github.mdx
While working on https://github.com/getsentry/sentry/pull/49379 I noticed a few instructions missing from the self-hosted GitHub instructions that I needed to address before getting the webhook to work as expected.
=> feat(github): Add webhook setup instructions

src/docs/sdk/performance/span-data-conventions.mdx
Per https://github.com/getsentry/team-webplatform-meta/issues/65 we want to define where HTTP status codes should be stored in events (200, 404, 500, etc)
Reasoning for why it is a problem, is that SDKs generally should not set tags "for" users on events.
=> Update span-data-conventions for HTTP.status_code

src/docs/sdk/performance/span-data-conventions.mdx
https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/#status
=> OTel Semantic convention

src/components/sidebar.tsx
Realized I forgot to add the Heroku docs to the sidebar in https://github.com/getsentry/develop/pull/827
=> ref(integrations): Add Heroku docs to sidebar

src/docs/api/public.mdx
Update `Making an API Public` section with more recent `@extend_schema` example, new `OpenApiExample` that includes `request_only=True` addition, and warning to update all requests in one endpoint in the same PR if multiple requests in the endpoint previously used manual JSON build.
=> docs(api): Update api instructions

src/docs/sdk/performance/span-operations.mdx
When implementing Tracing without Performance we may need to get rid of a required `op` when creating a `TransactionContext` in `Sentry.continueTrace` in some SDKs (e.g. Java). This mentions that we can use an `op` of `default` in such cases.
=> Mention default value for op can be usesd in SDKs as well

src/docs/sdk/client-reports.mdx
Mention new insufficient_data reason for client discard introduced in getsentry/snuba#4407.
=> docs(sdk): Add insufficient_data reason for client discard

src/docs/sdk/check-ins.mdx
Adds the optional `monitor_config` and `contexts` to the check-in payload
=> feat(crons): Add trace_id and config to check-in payload

src/docs/sdk/performance/trace-origin.mdx
Clarify that the integration part is omitted most of the time.
=> Trace Origin: Clarify integration part

src/docs/testing.mdx
- Handle multiple connections (as we have those now)
- Make all imports self contained so that the example is easier to copy/paste.
=> feat: Make SQL logging snippet better

src/docs/python-dependencies.mdx
This updates the dev docs to discuss the steps necessary before updating our `requirements` files. It also consolidates information on adding a new dependency with information on updating an existing dependency, since there's a great deal of overlap.
=> fix(python): Add information about `getsentry/pypi` to docs on Python deps

src/docs/sdk/performance/span-data-conventions.mdx
Added `url` and `type` for Span Data Conventions under mobile group.
Related to https://github.com/getsentry/sentry-cocoa/issues/2393
=> feat: Add more Mobile Span Data Conventions

src/docs/frontend/index.mdx
=> Fix typo: Removed an extra 'the' in index.mdx file

src/docs/api/public.mdx
Improve instructions for using OpenApi/drf-spectacular based on feedback
1. Specify requirement to add a docstring to the endpoint which shows as the endpoint description on the docs page
2. Clarify how to tag the endpoint in the correct tab and include an example
=> docs(api): Improve documentation instructions

src/docs/sdk/features.mdx
Either `sendDefaultPii` or another opt-in flag.
=> Mention request/response bodies for GraphQL should be guarded by a flag

src/docs/self-hosted/releases.mdx
To avoid db migration errors before upgrade to 23.7.0+
=> Add hard stop for 23.6.2 due to django upgrade

package.json, yarn.lock
Bumping the `@sentry/profiling-node` dependency as it solves an issue when starting the application. Without it, the application crashes.
=> chore(profiling): Bump profiling package

src/components/sidebar.tsx, src/docs/frontend/working-on-getting-started-docs.mdx
Add a user guide on how to add and update "getting started" docs in Sentry's main repository.
closes: https://github.com/getsentry/sentry/issues/53858
**Preview:**
=> feat(docs): Add getting Started docs guide

src/docs/environment/index.mdx
no more Docker.app support + the kafka thing is obsolete since devserver now guides the user to do that exact recommendation
=> devenv: remove Docker.app

src/docs/self-hosted/index.mdx
Without line breaks, the following paragraph is merged into the last list item.
=> fix: add line breaks in self-hosted overview

src/docs/integrations/github.mdx
This patch adopts the permissions table to actual GitHub's
- wording
- and section naming
=> Update github.mdx: Update permissions table 

src/docs/sdk/event-payloads/contexts.mdx
For normalizing where we store the HTTP response code in our events we invented the `response` context: https://github.com/getsentry/team-sdks/issues/9
This PR adds documentation on how this `response` context should look like.
=> Added response context

src/docs/api/basics.mdx, src/docs/api/checklist.mdx, src/docs/api/concepts.mdx, src/docs/api/design.mdx, src/docs/api/index.mdx, src/docs/api/public.mdx
Moving https://www.notion.so/sentry/WIP-API-Design-Standards-Expectations-5bb7ceb1266a4fbebf6cc14225fde7bb to api documentation.
=> docs(apis): Adding API basics

src/docs/sdk/event-payloads/index.mdx
This clarifies the current payload size limit for the `/api/PROJECT_ID/store/` endpoint, and makes it more like how the limit is described at https://develop.sentry.dev/sdk/store/#size-limits.
=> fix: 1MB limit is after decompression

src/docs/integrations/discord/index.mdx
You can't actually install the Discord integration locally without setting a redirect URI, but this was missing from the docs.
=> ref(discord): Add OAuth2 redirect URI

src/docs/frontend/network-requests.mdx
Direct link to the example is: https://develop-git-ryan953-doc-useapiquery-with-hooks.sentry.dev/frontend/network-requests/
See also: https://github.com/getsentry/sentry/pull/56288 where we fix all the examples in the app, so it's easier to copy+paste your way to success!
=> docs: Document how to setup hook tests that rely on useApiQuery

src/docs/environment/index.mdx
The `pyenv_setup.sh` script which runs when you call `make setup-pyenv` in the `sentry` repo only considers the case for zsh wherein the user has their zsh config in `~/.zprofile`. For anyone who doesn't, the script therefore doesn't work. This adds a note to the `zsh` tab of the code snippet telling people to do that part of the setup manually in that case.
=> docs(dev env): Add note about `.zshrc` to `make setup-pyenv` section

src/docs/api/public.mdx
`here` links to [this example](https://github.com/getsentry/sentry/blob/4828c60fd7f9fce5e32769054b9a7b10dc795aaa/src/sentry/replays/post_process.py#L43-L44)
=> chore(docs): Clarify private fields on response schema

src/docs/database-migrations.mdx
I remember when I first made a migration I followed the instructions and commented the SQL, only to have the action comment the same thing 😔
This should help people making their first migration avoid that mistake.
=> nit(docs): Update migration instructions w/ github action to generate sql

src/docs/transaction-clustering/index.mdx
We by now trust transaction clustering enough to mark every `url` transaction as `sanitized`, so the description can be simplified.
=> Update transaction clustering docs

src/docs/database-migrations.mdx
- Add example of deploying schema changes to large tables. We'd like to move away from having SRE run column add migrations and need to document the self-service flow.
- Revise TOC to contain more sections and less nesting.
=> feat: Add example for adding a column to a large table

src/docs/sdk/performance/span-operations.mdx
The [Strawberry GraphQL server integration](https://github.com/getsentry/sentry-python/pull/2393) in the Python SDK creates spans for parsing and validation. 
Preview: https://develop-git-sentrivana-patch-1.sentry.dev/sdk/performance/span-operations/
=> Add more GraphQL span ops

src/docs/sdk/performance/span-data-conventions.mdx
We didn't specify units in our docs, I added them to remove any ambiguity.
=> ref(docs): add units to PerformanceResourceTiming resource size properties

src/docs/database-migrations.mdx
We don't need to add columns with dangerous migrations anymore. All column adds can be done as deploy time migrations.
=> feat: Simpler column add migration guide

src/docs/api/public.mdx
Add information about how:
1. Nested serializers have their description populated by the nested class's docstring, not the `help_text` field
2. Model serializer fields get ordered by the `fields` attribute in the `Meta` class
3. inline_serializers work by adding an example
=> chore(docs): Add model serializer ordering and nested + inline serializer info

src/docs/environment/index.mdx
After enabling Relay and Kafka, the snuba container configuration needs to be updated, this only happens when re-creating the container.
Container creation is conditional on `SENTRY_EVENTSTREAM`:
https://github.com/getsentry/sentry/blob/9c487382d459203ebe4109f6b677507f03ca0891/src/sentry/conf/server.py#L2747-L2778
=> docs: Add note to restart snuba after enabling relay

src/docs/issue-platform.mdx
Link `/event-payloads` is dead, changing to `/sdk/event-payloads` which works and is most likely what's expected.
=> Link /event-payloads is dead, changing to /sdk/event-payloads

src/docs/self-hosted/backup.mdx, src/docs/self-hosted/index.mdx
Figured out install script showed "docker compose" but docs mentionned "docker-compose"
=> feat: Replace docker-compose with "docker compose"

src/docs/environment/index.mdx
The new `devenv` tool has now superseded bootstrap-sentry for bootstrap: https://github.com/getsentry/bootstrap-sentry/pull/55
And with it comes a lot of simplification (like no pyenv, and maintenance is only done with `devenv sync`) that obviates the need for a lot of these docs.
=> feat: devenv

src/docs/services/email.mdx
Update a TODO with information about how to set up the local mail preview so when you're developing you can actually trigger emails.
=> ref(mail): Add mail preview docs

src/docs/feature-flags/index.mdx
Documentation for https://github.com/getsentry/getsentry/pull/11996.
=> feat(features): Document trial plan tiers

src/docs/issue-platform.mdx
Add documentation updates for the work done in the crons/sd issue platform milestone
https://github.com/getsentry/sentry/milestone/66
Fixes https://github.com/getsentry/sentry/issues/58844
=> docs(issue-platform): Update docs from issue platform support additions

src/docs/sdk/event-payloads/user.mdx
This shouldn't be used as the feature in the product was never implemented.
=> Remove `user.segment`

src/docs/sdk/envelopes.mdx
Documents maximum `check-in` size payload in accordance with relay:
https://github.com/getsentry/relay/blob/ee1fc80b46968d803c4a90f6b3ed36c07955fdad/relay-config/src/config.rs#L586
=> docs(crons): Document check-in envelope size limit

src/docs/delightful-developer-metrics/sending-metrics-sdk.mdx
Documenting missing capability/example to send timers
=> Add timer to sending-metrics-sdk

scripts/bump-version.sh
Undoes the deletion in https://github.com/getsentry/develop/pull/1088, but no longer changes the LICENSE. This is necessary to unbreak the release script.
=> feat(backup): Revive stub bump-version.sh

.craft.yml, scripts/bump-version.sh
preReleaseCommand is an optional parameter, when set to empty string, does not run the usual preReleaseCommand script
https://github.com/getsentry/craft/blob/a3844c57fb10ec5265756814fa73cc88291a5d2d/src/commands/prepare.ts#L234
=> Set preReleaseCommand to empty string

src/docs/environment/index.mdx
This is a follow up to GH-1037, recommending dev.getsentry.net for the
`sentry devserver` (we already recommended this for `yarn dev-ui`).
=> ref(devserver): Recommend dev.getsentry.net for devserver

src/docs/environment/index.mdx, src/docs/frontend/development-server.mdx
This works after https://github.com/getsentry/sentry/pull/60673
=> feat(https): Add HTTPS setup for devserver

src/docs/self-hosted/backup.mdx
These docs now mention the newly introduced relocation scopes, as well as the `sentry-admin.sh` tool.
=> doc(backup): Update relocation docs

src/docs/sdk/check-ins.mdx
Adds issue threshold values to documented monitor config.
Follow up from https://github.com/getsentry/relay/pull/2842
=> feat(crons): Add issue thresholds to MonitorConfig

src/components/sidebar.tsx, src/docs/frontend/component-library.mdx
You should be able to visit the Component Library on any sentry instance, like on sentry.io: https://sentry.io/orgredirect/organizations/:orgslug/stories/
This is the first pass at some docs about it. Why we have it, how to get there, how to contribute and some ideas for the future!
=> docs(stories): Add some initial docs for the /stories/ Component Library

src/docs/frontend/component-library.mdx
Related to https://github.com/getsentry/sentry/pull/62229#pullrequestreview-1793692363
=> docs(stories): Add a note about using storyBook() with hooks and HoC wrappers

src/docs/environment/index.mdx
- we're not on python 2
- we're using pyuwsgi
- uwsgi no longer needs to match the compiled python
=> ref: remove outdated instructions about uwsgi

src/docs/frontend/component-library.mdx
Introduced with https://github.com/getsentry/sentry/pull/62726 
I think it's handy to
1. Be explicit that theme is something this component cares about (and does well)
2. Not force the reader to switch themes. ie: if they're reading at night, flashing the whole page into light mode is annoying
=> docs(ui-lib): Write a blurb about the <ThemeToggle> UI Component Library helper

src/docs/environment/index.mdx
Explain how to solve Android emulator events not showing up in local Sentry instance.
=> Add Android emulator localhost troubleshooting

src/docs/sdk/check-ins.mdx
Added in https://github.com/getsentry/relay/pull/2842
ref https://github.com/getsentry/team-sdks/issues/43
=> Add new thresholds to monitor config payload

src/docs/sdk/check-ins.mdx
Reverts getsentry/develop#1132
Woops was already there - added in https://github.com/getsentry/develop/pull/1108, my mistake
=> Revert "Add new thresholds to monitor config payload"

src/docs/self-hosted/csp.mdx
django-csp middleware has been enabled by default in https://github.com/getsentry/sentry/pull/57130
So we no longer need this if condition.
=> docs(csp): remove if condition for CSP middleware

vercel.json
Previously CSP violations from https://docs.sentry.io and https://develop.sentry.dev/ were intermixed in a single `docs-csp` Sentry project.
Now we are going to report them to a separate `develop-csp` project: https://sentry.sentry.io/issues/?project=4506631158300672
=> Report CSP violations to a separate Sentry project

src/docs/api/design.mdx
We dont' use CamelCase, we use camelBacked. While camelBack is generally synonymous with CamelCase, the first letter should be lowercase.
=> Update case naming

src/docs/self-hosted/releases.mdx
According to the example config file, it should be `PyMemcacheCache` not `PyMemcachedCache`
=> docs: resolve typo in Breaking Changes part of self-hosted docs

src/docs/sdk/event-payloads/contexts.mdx
Added new fields to trace context which could be set by SDKs and are typed out in Relay
related to: https://github.com/getsentry/relay/pull/3104
=> feat(contexts): Describe additional fields which can be set by SDKs in trace context

src/components/sidebar.tsx, src/docs/sdk/performance/frames-delay.mdx, src/docs/sdk/performance/span-data-conventions.mdx
Add docs for the performance metric frames delay.
=> Add frames delay

src/docs/sdk/craft-quick-start.mdx
This PR adds documentation to our Craft/publishing setup guide in the develop docs: Since we completed the work on https://github.com/getsentry/publish/issues/3441, we now document how to configure a repo's publishing process to use multiple craft configs, depending on the selected merge target branch.
=> feat: Document new multi craft config feature

src/docs/self-hosted/index.mdx
A while ago, Chad created a new label on self-hosted repo. The label is used to track preview features.
Adding this to docs helps guide people to the right path for enabling new features.
/cc @chadwhitacre @azaslavsky @hubertdeng123
=> docs(self-hosted): enabling preview features section

src/docs/sdk/metrics.mdx
Clarifies
* when normalization should be applied
* that the flush interval should be 5s
* the `before_emit_metric` hook
=> chore(metrics): Clarify SDK implementation details

src/docs/environment/index.mdx
...as `devservices` need to be started before running the `devserver`
=> docs(environment): Add devservices script to setup

src/docs/delightful-developer-metrics/sending-metrics-abstraction.mdx, src/docs/delightful-developer-metrics/sending-metrics-sdk.mdx
This PR fixes some issues in the metrics docs when it came to emitting metrics with the `sentry_sdk` or our internal Python abstraction.
=> fix(ddm): Fix docs for metrics

src/docs/sdk/hub_and_scope_refactoring.mdx
I've tried to summarize what was discussed in yesterdays meeting regarding why we need to get rid of hub.
Preview: https://develop-git-adinauer-patch-1.sentry.dev/sdk/hub_and_scope_refactoring/
=> Hubs and Scopes changes reasoning

src/docs/sdk/metrics.mdx
Clarify the span creating mode docs based on the [metric correlation RFC](https://github.com/getsentry/rfcs/blob/main/text/0123-metrics-correlation.md#basics).
=> chore(metrics): Clarify metrics span seeking/creating mode

src/docs/sdk/overview.mdx
Explain what the various subdomains are in a DSN and explain the backwards compatibility for US accounts
=> chore: Expand DSN docs to cover subdomain semantics.

src/docs/sdk/envelopes.mdx
- Linked rfc https://github.com/getsentry/rfcs/blob/main/text/0033-view-hierarchy.md
Used mainly in mobile SDKs
- JS PR https://github.com/getsentry/sentry-javascript/pull/11197
=> Add view hierarchy to attachment types

src/docs/sdk/hub_and_scope_refactoring.mdx
Rendered preview: https://develop-git-ivana-old-to-new-hub-api.sentry.dev/sdk/hub_and_scope_refactoring/#what-does-the-new-api-look-like
=> Add a mapping from old to new hub API

src/docs/sdk/distributed-tracing/index.mdx, src/docs/sdk/features.mdx, src/docs/sdk/performance/dynamic-sampling-context.mdx, src/docs/sdk/performance/index.mdx
https://github.com/getsentry/team-sdks/issues/41
=> W3C traceparent

src/docs/sdk/overview.mdx
related: https://github.com/getsentry/team-sdks/issues/61
=> Add expected User-Agent format to SDK docs

src/docs/self-hosted/index.mdx
Add link to workshop until April 30th, then change to recorded video once date passes.
=> Add link to live workshop about migrating to SaaS

src/components/layout.tsx, src/css/_includes/grid.scss, src/css/_includes/sidebar.scss
**Before** you'd often have cases like this where the main content is gone, and you're scrolling to find some item in the sidebar:
**After** the sidebar has it's own scrollbar, so you can be at the top of the content, and still nav around:
There are three breakpoints to check:
1. >=992px is the 3 column layout
In this layout both the left & right "On this page" sidebars are sticky
2. >=768px && <992px is a 2 column layout
The right sidebar drops to the bottom of the page
4. <768px is one column
The left sidebar stacks on top of the content, right sidebar is still below.
Left sidebar can be toggled with the big "Table of contents" button at the top.
There's one buggy thing visible in the 2nd screenshot above. When the content is scrolled & the sidebar becomes sticky, the height of the …
=> Let the sidebar scroll independant of the main content

src/components/sidebar.tsx
I just removed this page in https://github.com/getsentry/develop/pull/1239, need to remove the link as well
=> docs(frontend): Remove sidebar link to old DefaultProps frontend page

src/components/sidebar.tsx, src/docs/sdk/event-payloads/index.mdx, src/docs/sdk/event-payloads/lockreason.mdx
As discussed - Lock Reason is not a top level field but rather part of the threads interface. This PR aims to reflect that by removing it from the sidbar and Event Paylods index page, and adding a note to that effect
=> chore(lockreason): Update Lock Reason docs

src/docs/sdk/event-payloads/sdk.mdx
Add a new field features to the SDK event payload, which is handy for tracking the adoption of features.
This is for https://github.com/getsentry/team-sdks/issues/83.
=> Add SDK features to event payload

src/docs/sdk/event-payloads/contexts.mdx
There is already `device.arch` but I couldn't find a suitable property to include the app arch. 
The app and device architecture can differ, for example when running through Rosetta or Windows WOW64 emulation.
I also fixed a couple of typos!
=> feat: Add `app.app_arch` context

src/docs/sdk/event-payloads/contexts.mdx
Users of the Native SDK would prefer to identify and search for Linux distributions their events come from: https://github.com/getsentry/sentry-native/issues/943.
After a preliminary implementation (https://github.com/getsentry/sentry-native/pull/963 and https://github.com/getsentry/relay/pull/3443), I think it is time to nail down the specification of the context attributes.
I consider the current naming of the attributes to be preliminary. I didn't want to force the naming scheme from `/etc/os-release` onto the attributes here (but maybe we should?), and the selection of the attributes is also a bit arbitrary. 
Only `name` and ` version` make sense as indexable entries because the support of other attributes varies wildly between distributions (not only in availability but sometimes …
=> feat: add Linux distributions to the os context

src/docs/sdk/performance/span-data-conventions.mdx
Add `ui.ui.contributes_to_ttid` and `ui.ui.contributes_to_ttfd` to the span data bag. The SDKs should set those flags on all spans which contribute to ttid / ttfd.
I'm still not 100% happy with the naming, if you have something better in mind, feel free to suggest!
Based on previous discussions here: https://www.notion.so/sentry/span-contribution-9b5a0979a81645789db6877593729cf4
Java impl: https://github.com/getsentry/sentry-java/pull/3386
Preview deeplink: https://develop-git-feat-ttidttfdcontributingflags.sentry.dev/sdk/performance/span-data-conventions/#ui
=> Add ttid/ttfd contribution flags to span data convention

src/docs/sdk/performance/modules/app-starts.mdx, src/docs/sdk/performance/modules/caches.mdx, src/docs/sdk/performance/modules/index.mdx, src/docs/sdk/performance/modules/queries.mdx, src/docs/sdk/performance/modules/queues.mdx, src/docs/sdk/performance/modules/requests.mdx, src/docs/sdk/performance/modules/resources.mdx, src/docs/sdk/performance/modules/screen-loads.mdx, src/docs/sdk/performance/modules/web-vitals.mdx
This are all the performance modules we currently have. We should document what makes spans eligible to show up in those modules, to make it easier for all the SDKs implement those requirements in their auto instrumentation (and to make it also easy to add documentation for manual instrumentation that should fill those modules with data.)
=> Empty pages for all performance modules. To be filled in separate PRs

src/docs/feature-flags/index.mdx
We generally prefer people to use options automator, so remove references to flagr. We can update this with instructions for flagpole once it is completed.
=> chore(feature-flags): Remove references to flagr

src/docs/integrations/discord/index.mdx, src/docs/integrations/pagerduty.mdx, src/docs/integrations/slack/index.mdx, src/docs/self-hosted/email.mdx, src/docs/self-hosted/index.mdx, src/docs/self-hosted/sso.mdx
Closes [#2996](https://github.com/getsentry/self-hosted/issues/2996)
/cc @hubertdeng123 @azaslavsky @stayallive
=> docs(self-hosted): recommend users to rerun install.sh for restart

src/docs/architecture.mdx
Include multi-region architecture diagram and context on how other diagrams fit together.
=> feat(hybridcloud) Expand architecture docs

src/docs/sdk/metrics.mdx
This PR updates our develop docs with the updated limits for metric name and unit lengths.
Related to: https://github.com/getsentry/relay/pull/3628
=> feat(metrics): Add maximum length for metric components

src/docs/sdk/performance/modules/requests.mdx
- explain required vs. optional parameters
- clean up structure
- add more detail to example
=> feat(insights): Strengthen Requests module docs

src/docs/analytics.mdx
this pr adds a line about testing analytics events locally
=> docs(analytics): Add info about testing locally

src/docs/dynamic-sampling/the-big-picture.mdx
This PR updates the dynamic sampling docs to clarify rate limiting and trace completeness.
Closes: https://github.com/getsentry/team-ingest/issues/315
=> feat(docs): Clarify rate limiting and trace completeness

src/docs/sdk/metrics.mdx
Neither Relay nor storage support multi-value tags.
Fixes https://github.com/getsentry/relay/issues/3691.
=> doc(metrics): Metric tags can only have a single value

src/docs/feature-flags/flagpole.mdx, src/docs/feature-flags/index.mdx
Adds the most commonly used context properties, their types, and a brief description of each to aid in flagpole feature creation.
Also adds a note about deployment timing for flagpole options in SaaS.
=> chore(flagpole): Updates documentation with commonly used context properties

src/docs/sdk/performance/modules/assets.mdx, src/docs/sdk/performance/modules/index.mdx, src/docs/sdk/performance/modules/resources.mdx
=> feat(insights): asset module documentation

src/docs/database-migrations.mdx
just a small language update since we no longer use `is_dangerous` + added the small but crucial last step of running a post-deploy migration :)
=> docs(migrations): Update is_dangerous -> is_post_deployment

src/docs/sdk/unified-api/index.mdx
It is not entirely clear from reading this that you can set anything as context, not just the valid keys.
=> fix: Clarify context keys

src/docs/backend/development-server.mdx, src/docs/environment/index.mdx
Clarify how ngrok should be setup for siloed and non-siloed modes.
Refs getsentry/sentry#14423
=> fix: Improve ngrok setup docs

src/docs/database-migrations.mdx
There are currently no docs describing how to resolve failing backup tests in CI when adding a new model. This PR adds these docs to the develop page on migrations.
=> feat(migrations): add docs for snapshots & backup testing

src/docs/sdk/basics.mdx
Channel is Archived on discord. updated channel is
=> Discord "SDK Contributor" chat is no longer used. Moved to "SDK-Chat"

src/docs/environment/index.mdx
The subsubheadings 'Frontend Only & Backend Only'/'Enabling HTTPS'/'Ingestion Pipeline (Relay)' are not specific to Getsentry, so it makes more sense for them to be structured under the Sentry subhead.
Additionally clarify which settings should be used when configuring the devserver for error ingestion vs metrics ingestion.
=> fix(environment): restructure subheadings and clarify ingest setup

src/docs/sdk/event-payloads/contexts.mdx
Note: Should only be merged once https://github.com/getsentry/sentry-javascript/pull/12639 is released.
=> feat: Add docs for missing instrumentation context

src/docs/database-migrations.mdx
Received a helpful tip for this, thought it would be nice to put it in the docs
=> feat(migrations): Advertise --reuse-db command for migration test

src/docs/feature-flags/flagpole.mdx, src/docs/feature-flags/index.mdx
- Include api_expose
- Add `sentry_singletenant` context variable.
=> chore(features) Update feature flagging docs

src/docs/sdk/event-payloads/contexts.mdx
Add start_type to the app context, which both sentry-java and sentry-cocoa already send.
=> feat(contexts): Add app start type

package.json, yarn.lock
i can't build these docs locally on mac arm because @sentry/profiling-node 1.1.2 mispackaged executables like this:
```
node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-darwin-arm64-83.node:  ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, not stripped
```
this was fixed in @sentry/profiling-node 1.2.0
=> fix(build): fix on mac arm

src/docs/feature-flags/flagpole.mdx
Documentation changes to go with getsentry/getsentry#14867
=> Update flagpole documentation for single-tenant

src/docs/self-hosted/releases.mdx
The recommended 23.6.2 -> latest is no longer viable, 23.6.2 at this point is over a year old and https://github.com/getsentry/self-hosted/issues/3257 reports that going to 23.11.0 first was necessary. So I've added that and also streamlined the upgrade docs a bit.
I can't reproduce this on mac arm (can't install 23.6.2, linux/arm64/v8 images are missing for some services), but on mac linux I reproduced.
I can't access the Vercel previews but this is what it looks like locally:
=> self-hosted: update upgrade path
