getsentry/develop

- gatsby-config.js
- package.json
- src/components/externalLink.js
- src/components/layout.js
- src/components/sidebar.js
- src/css/_includes/icon.scss
- src/css/_includes/sidebar.scss
- src/css/screen.scss
- yarn.lock
- Add callout box
- Add last edit author/datetime
> Take two on GitHub call to action

- src/components/sidebar.js
- src/docs/frontend/defaultprops.mdx
- src/docs/frontend/index.mdx
- src/docs/frontend/migration-gridemotion.mdx
Fewer places for documentation to live. I can archive the other repository if people are happy with this.
> Move frontend handbook to this repository

- package.json
- src/components/codeBlock.js
- src/css/_includes/code-blocks.scss
- src/docs/docs-components.mdx
- yarn.lock
This adds a copy to clipboard button to all code blocks.
> feat: Added copy to clipboard to code blocks

- gatsby-config.js
- src/components/codeBlock.js
- src/components/codeTabs.js
- src/components/layout.js
- src/css/_includes/code-blocks.scss
- src/docs/docs-components.mdx
- src/docs/sdk/overview.mdx
- src/utils.js
This adds a DSN selector to the code blocks. Uses the getsentry API.
> feat: Added DSN selector to code blocks

- src/components/codeBlock.js
- src/components/codeTabs.js
- src/components/layout.js
- src/css/_includes/code-blocks.scss
This depends on cross domain sessions which doesn't work with fetch. sadface.
> fix: CORS for DSN

- src/components/sidebar.js
- src/docs/services/devservices.mdx
- src/docs/testing.mdx
Include a summary of what I cover in my onboarding session for testing.
> feat: Add testing docs

- README.md
- src/components/search/hitComps.js
- src/components/sidebar.js
- src/docs/frontend/defaultprops.mdx
- src/docs/services/digests.mdx
Spelling fixes I've collected as I've been working with `develop`.
> chore: Spelling fixes

- package.json
- plugins/gatsby-plugin-code-tabs/index.js
- src/components/codeBlock.js
- src/components/codeTabs.js
- src/css/_includes/code-blocks.scss
- src/docs/docs-components.mdx
- yarn.lock
> ref(ui): Make code blocks beautiful

- src/docs/testing.mdx
Include content on the datetime helpers that make building events much easier in tests.
> feat: Improve testing docs

- src/docs/integrations/github.mdx
Original Pull Request: https://github.com/getsentry/sentry-docs/pull/1622
> Add note about spaces in GitHub App name

- gatsby-config.js
- package.json
- plugins/gatsby-plugin-sentry/gatsby-browser.js
- plugins/gatsby-plugin-sentry/package.json
- yarn.lock
This is pulled in from https://github.com/dcramer/dcramer.github.com, and is based on the official gatsby-plugin-sentry (which cannot support APM as built).
> Add Sentry plugin

- src/docs/config.mdx
This PR adds some hints about why log messages might not appear.
> doc: more logging tips

- src/components/sidebar.js
- src/docs/environment.mdx
- src/docs/frontend/storybook.mdx
Migrate this content from notion to here. Once my CI changes are merged
I'll migrate the staging environment docs.
> Add getsentry setup and storybook content

- gatsby-config.js
> ref(config): Increase trace sample rate

- package.json
- yarn.lock
This should make the plugin work.
See CHANGELOG here: https://github.com/getsentry/sentry-javascript/blob/master/CHANGELOG.md#5190
> fix(deps): Upgrade @sentry/gatsby

- src/components/sidebar.js
- src/docs/architecture.mdx
Adds Event Ingestion Pipeline (externa link) to page.
Fixes #74
> Add Architecture page

- src/components/sidebar.js
- src/docs/environment.mdx
- src/docs/index.mdx
- src/docs/sentry-vs-getsentry.mdx
- src/docs/workflow.mdx
Also, some minor refactor + shuffling around.
> feat: add sync-getsentry into new workflow section

- package.json
- yarn.lock
> chore: Upgrade Sentry JS SDK

- src/components/sidebar.js
- src/docs/integrations/index.mdx
- src/docs/integrations/vercel.mdx
Do not merge this until https://github.com/getsentry/sentry-docs/pull/1854 is merged, the link to the Vercel docs doesn't exist yet.
> feat(Vercel): Add on prem user docs

- src/docs/environment/index.mdx
This addresses two problems I ran into when running through the dev environment instructions while setting up a new laptop.
> fix(dev environment): Add brew flag so progress is shown

- src/docs/sdk/event-payloads/contexts.mdx
UI PR for this change can be found here: https://github.com/getsentry/sentry/pull/20184
> Add state context docs

- src/docs/sdk/sessions.mdx
Hm, how can we improve the `auto_session_tracking` option to better reflect the different modes?
> docs: Clarify Session Modes and improve other docs

- src/components/sidebar.js
- src/docs/self-hosted/mail.mdx
See https://app.asana.com/0/1169344595888357/1190341230301191/f.
Closes getsentry/onpremise#565
> feat(self-hosted): Add docs around mail setup

- src/components/sidebar.js
- src/docs/pii/index.mdx
- src/docs/pii/methods.mdx
- src/docs/pii/selectors.mdx
- src/docs/pii/types.mdx
Imports the PII format docs from Relay into the "Application" section.
> feat(pii): Import PII docs from Relay

- src/docs/sdk/event-payloads/breadcrumbs.mdx
> ref(breadcrumbs-interface): Make little format adjustments

- src/docs/sdk/event-payloads/contexts.mdx
Add some additional information that would have helped me when deciding to use a context or an interface for measurements. Knowing that the SDK interface is does not support merging can be helpful context.
> feat(events) Add more context on contexts

- src/components/sidebar.js
- src/docs/sdk/unified-api/tracing.mdx
Not meant to be perfect, but to reorganize from bullet points into
SDK-sections and clarify a few points. Still plenty to do.
> feat: Rewrite Guidelines for Tracing support

- src/docs/pii/methods.mdx
see https://github.com/getsentry/relay/pull/760
> fix: Remove unused PII config APIs

- src/docs/sdk/sessions.mdx
> feat: Add instructions for local sessions ingestion

- src/docs/sdk/event-payloads/stacktrace.mdx
> fix link to stacktrace

- .prettierrc
- src/components/codeBlock.js
- src/components/codeTabs.js
- src/components/jsonschema.js
- src/components/layout.js
- src/components/seo.js
- src/utils.js
- src/utils/algolia.js
This repo was lacking a .prettierrc file, leading to inconsistent styling with other repos. This PR pulls the config of getsentry/sentry-docs and reformats all the files accordingly.
> ref(prettier): Copy in .prettierrc from sentry-docs

- src/components/sidebar.js
- src/docs/sdk/index.mdx
- src/docs/sdk/philosophy.mdx
No reason for this doc not to be public.
> Add SDK philosophy to develop docs

- yarn.lock
Run `yarn-deduplicate yarn.lock` to deduplicate packages.
> build(yarn): Deduplicate packages

- gatsby-node.js
- src/components/dynamicNav.js
- src/components/sidebar.js
- src/components/sidebarLink.js
- src/css/_includes/sidebar.scss
- src/docs/environment/u2f.mdx
This also improves sidebar capabilities (pulls in some stuff from docs) to support subnav and auto generation.
> feat: Add docs for configuring u2f in development

- src/docs/testing.mdx
Pairs with https://github.com/getsentry/sentry/pull/21484, like fine wine.
> feat: new SENTRY_SCREENSHOT incantation

- src/docs/sdk/event-payloads/index.mdx
Added the size limit for event payload size.
> Add: event payload size limit

- src/components/createGitHubAppForm.tsx
- src/components/markdown.tsx
> fix(github-sso): Fix GitHub SSO app form

- README.md
There were various ways of initializing the project and some duplicated content.
> docs: Clean up the README file

- src/docs/sdk/event-payloads/breadcrumbs.mdx
Related to the PR https://github.com/getsentry/sentry/issues/8133
> ref(sdk-breadcrumbs): Add Breadcrumb timestamp info

- src/docs/self-hosted/geolocation.mdx
> Remove question mark from heading for consistency

- src/docs/sdk/event-payloads/index.mdx
- src/docs/sdk/sessions.mdx
This goes hand-in-hand with https://github.com/getsentry/sentry-docs/pull/2793.
> Update release format to match suggested pattern

- src/docs/sdk/features.mdx
Add documentation to expected features for the implementation of the attachments API.
Fixes GH-223
> feat: Document attachments API

- src/components/sidebar.tsx
- src/docs/self-hosted/backup.mdx
Fixes getsentry/onpremise#506, fixes getsentry/onpremise#364.
Related: https://app.asana.com/0/1169344595888357/1190341230301185
> feat(self-hosted): Add docs around backup/restore

- src/docs/self-hosted/releases.mdx
Arrived here from self-hosted TSC conversation today. Small mitigation ahead of https://github.com/getsentry/onpremise/issues/854.
> Warn folks about the true meaning of CalVer

- src/docs/integrations/github.mdx
`github-app.id` should be an int value otherwise it raises error.
> docs: update github.mdx

- src/components/sidebar.tsx
- src/docs/self-hosted/index.mdx
- src/docs/self-hosted/troubleshooting.mdx
This section now covers the most commin questions/issues we get regarding self-hosted. It also addresses https://app.asana.com/0/1169344595888357/1188448821391289 meaning it fixes getsentry/onpremise#478, and fixes getsentry/onpremise#788.
> feat(self-hosted): Add a dedicated troubleshooting section

- src/docs/sdk/overview.mdx
Addresses https://github.com/getsentry/sentry-docs/issues/1635
See also https://github.com/getsentry/sentry-docs/pull/3096
> Clarify effects of empty DSN

- src/components/sidebar.tsx
- src/docs/integrations/index.mdx
- src/docs/integrations/pagerduty.mdx
PagerDuty development docs. For a preview, see the vercel link 👇 .
> feat(pagerduty): Add develop docs

- src/docs/testing.mdx
Use the name of the thing we're actually using.
> fix: Percy no longer exists

- src/docs/processing-tickets.mdx
> SLA communicates more commitment than is wanted

- src/docs/sdk/performance.mdx
I'm sure it can be better described, but I believe currently its a bit misleading
> Clarify that 0.0 sampling can sample

- src/components/sidebar.tsx
- src/docs/frontend/using-hooks.mdx
A follow up to the discussion of the March 11th frontend TSC.
> feat: Start hooks guide

- package.json
- src/utils/algolia.ts
- yarn.lock
This makes some updates to the search lib and config which result in less data being fetched
> Feat: smaller faster search

- src/docs/sdk/event-payloads/contexts.mdx
This documents some missing properties which already have made it into the spec.
cc @marandaneto and @bruno-garcia
> Document missing properties

- src/docs/sdk/performance.mdx
> fix: typo (Sentrt -> Sentry)

- src/components/sidebar.tsx
- src/docs/sdk/features.mdx
- src/docs/sdk/overview.mdx
- src/docs/sdk/rate-limiting.mdx
Initial documentation for guiding SDK implementations.
> Category-based rate limiting with X-Sentry-Rate-Limits

- src/docs/self-hosted/index.mdx
This is in relation with getsentry/sentry#26567 and getsentry/onpremise#983
> ref(self-hosted): Add upgrade paths w/ hard-stops

- src/docs/environment/index.mdx
I bumped into a few issues while setting up the environment while using fish as my shell, so this fixes those up and performs a bit of additional cleanup.
Setup script updates: https://github.com/getsentry/sentry/pull/26511
> Fix pyenv setup for fish

- src/docs/self-hosted/geolocation.mdx
https://forum.sentry.io/t/geolocation-doesnt-work-on-default-sentry/14381
> Add a note about geoipupdate behavior

- src/docs/sdk/features.mdx
See: https://github.com/getsentry/sentry-java/pull/1559/
> ref: sdk http client convention

- src/docs/sdk/envelopes.mdx
@jan-auer can you verify please?
Ref https://github.com/getsentry/sentry-javascript/issues/3762
> docs(envelope): Add note regarding envelope header authentication

- src/docs/sdk/research/performance/index.mdx
> Document tracing issues related to scope propagation

- src/docs/self-hosted/email.mdx
Alternative to https://github.com/getsentry/onpremise/pull/964 to address https://github.com/getsentry/onpremise/issues/965.
> Add warning about email config layering

- src/docs/self-hosted/releases.mdx
Follow up to https://github.com/getsentry/develop/pull/405#discussion_r690410946
> feat(self-hosted): Pull out configuration update notice

- src/docs/environment/index.mdx
- src/docs/sdk/performance/trace-context.mdx
Some typo fixes I had hanging around in my working directory, along with a decent dose of autoformatting (which ran when I saved the files).
No content changes.
> fix(various): Fix typos and apply autoformatting changes

- src/docs/integrations/slack/index.mdx
Update the Slack developer docs to reflect the newest version of our app.
> ref(slack): Update Slack docs

- src/docs/code-review.mdx
To track changes made back ti issues in Jira (User Stories, Customer Issues, ...) add the Jira ID to the commit message. This shows braches, commits, pull-requests and their status in Jira. Example here: https://getsentry.atlassian.net/browse/INGEST-293
> ref(review): Add Jira link to pull request names

- src/docs/sdk/performance/index.mdx
Closes https://github.com/getsentry/develop/issues/298
> Docs maxSpans

- src/docs/services/queue.mdx
This updates the recommendations to clarify what is being done and
give more hints on the contraints to keep in mind.
It also adds a new recommendation that's currently being orally passed
around.
----
Please add more reviewers as fit, I mostly know VIE folks :)
> docs(celery): Add new recommendation and clarify them

- src/docs/sdk/event-payloads/contexts.mdx
> feat: Deprecate lang & timezone of device context

- src/docs/sdk/client-reports.mdx
> Document client reports for relay outcomes

- src/docs/self-hosted/email.mdx
https://github.com/getsentry/self-hosted/issues/1202
> Link to GH issues for internal MX

- src/docs/self-hosted/troubleshooting.mdx
Following https://github.com/getsentry/self-hosted/pull/1248
> Add Docker Containers' Healthcheck to troubleshooting doc

- src/docs/code-review.mdx
Add a few more points to consider during code review.
> ref: Improve Code review docs

- src/docs/api/public.mdx
- Update small mistakes / broken commands
- Flesh out examples more with annotated concrete examples
- Add more helpful links
> feat(docs): update dev api doc instructions

- src/docs/api/public.mdx
Add note in tips for `make diff-docs`
> surface make diff-docs

- src/docs/environment/index.mdx
See changes for a description.
> fix(devenv): Caveats for starting ingest with flags

- src/docs/sdk/client-reports.mdx
> fix: Specify data categories for client reports

- src/docs/testing.mdx
Documents https://github.com/getsentry/sentry/pull/33071
> Document db misuse detector

- src/docs/sdk/client-reports.mdx
A reminder for people who plan on adding new reasons to also add it to the allowlist in snuba.
> New reasons have to be added to snuba as well

- src/docs/sdk/client-reports.mdx
Document that we do not track SDK bugs with client reports
> SDK bugs and client reports

- src/docs/sdk/event-payloads/contexts.mdx
See also https://www.notion.so/sentry/Conflicting-OS-contexts-6b4b157034c54c02a97ea8523bee265d#6aa1e8cc97f4444bb33d180ecf7c3adf
> doc: Clarify the existence of client_os

- src/docs/sdk/client-reports.mdx
Document that client reports never get rate limited.
> Client reports get never rate limited

- src/docs/services/email.mdx
https://github.com/getsentry/self-hosted/pull/1446
https://github.com/getsentry/sentry/issues/34387
> Document full name email format

- src/docs/api/public.mdx
> fix(api-docs): Incorrect command

- .github/workflows/prepare-release.yml
This is more accurate and is something I've been wanting to do all over the place so let's start here ... because since @BYK is the last person to have committed to this file GH is spamming him when action runs fail.
Partially addresses #579, still need to figure out why releases are failing tho. 🧐
> Release => Prepare Release

- src/docs/self-hosted/index.mdx
https://github.com/getsentry/self-hosted/pull/1479
> Document enhance-image.sh

- src/docs/config.mdx
Closes https://github.com/getsentry/sentry/issues/34760.
> Talk more about url-prefix path (i.e., nope)

- src/components/sidebar.tsx
- src/docs/signal-handlers.mdx
> Added documentation on signal handlers

- src/docs/docs/index.mdx
- src/docs/sdk/overview.mdx
In the past the SDks had the name "Raven". Those times are long gone, so I removed the last two mentions of this ancient name, to not confuse new users.
> Removed mentions of "Raven".

- src/docs/api/public.mdx
https://github.com/getsentry/sentry-docs/pull/5151
> Update reference to script that moved

- src/docs/integrations/vercel.mdx
Some slight edits to scopes as Vercel issued a recent bug fix + a better explanation of where to find secrets.
> ref(vercel): Update API Scopes + instructions

- src/docs/environment/index.mdx
This documents the previously only internally documented bootstrap script.
> Document bootstrap.sh script

- src/docs/database-migrations.mdx
Document testing migrations with the `TestMigrations` base class.
Preview of the relevant section is here: https://develop-git-test-migrations-testing.sentry.dev/database-migrations/#testing
> Add docs for migration testing [INC-160 INGEST-1436]

- src/docs/sdk/features.mdx
@bruno-garcia can you please provide more details on the .NET version of this feature.
See here for more info: https://github.com/getsentry/develop/issues/539
> Document log context feature

- src/docs/sdk/event-payloads/user.mdx
Align with the Relay spec: https://github.com/getsentry/relay/blob/7fb4ef6546cbe27c2b6e101dc46fd36cbe273d57/relay-general/src/protocol/user.rs#L67-L69
> Add user segment to user payload docs

- src/docs/sdk/performance/span-operations.mdx
Hopefully this also fixes broken master
> Reference latest operations breakdown code

- README.md
> Fix sentence fragment

- src/docs/sdk/performance/span-operations.mdx
(and added comment to subprocess to make clear what it does.)
> Added span op for "async tasks"

- .github/workflows/test.yml
Fixes build errors in https://github.com/getsentry/develop/pull/714, https://github.com/getsentry/develop/pull/716, https://github.com/getsentry/develop/pull/717
ref: https://github.com/volta-cli/action/issues/117
> build: Upgrade volta cli to v4 pin

- gatsby-node.js
- package.json
- src/gatsby/createPages.ts
- src/gatsby/onCreateNode.ts
- yarn.lock
@JonasBa Some stuff I tried out the other week.
Putting profiling into bundlers/build tooling is very interesting, and could be a nice immediate value add for us esp since we are thinking about doing more work with bundlers.
> experiment with adding Profiling to measure Gatsby builds

- src/docs/sdk/craft-quick-start.mdx
I chatted with @asottile-sentry about this. It feels wrong to me to have a different capitalization style on one page of our docs. Pixels matter!
> Capitalize "Craft Quick Start" doc

- src/docs/database-migrations.mdx
related https://github.com/getsentry/getsentry/pull/8669
> update docs for column delete

- src/docs/workflow.mdx
https://getsentry.atlassian.net/browse/DEVINFRA-128
> replace #sync-getsentry directions with working ones

- src/docs/sdk/performance/opentelemetry.mdx
Just align this better with the current state of things.
> feat(otel): Update base otel spec code

- src/docs/sdk/sessions.mdx
Clarify that rate limited events should update the session.
> Clarify rate limited events update session

- src/docs/self-hosted/troubleshooting.mdx
As per discussion on discord, this adds documentation for another way to clean up postgres for self-hosted
> Add another way to clean up disc space for postgres

- src/docs/workflow.mdx
Because upper cases should not be discriminated against :P
> Add uppercase to requires string

- src/docs/workflow.mdx
Editing the PR after the fact won't trigger an action.
> Add note about only working when opening PR

- src/docs/sdk/unified-api/index.mdx
> add start/end session to static api documentation

- src/docs/sdk/performance/opentelemetry.mdx
1. e892ea4ef3c4066f5eefefaa870e99f86317d1bb: add logic that covers linking errors to transactions via an event processor
2. 8e856af16aa53c0323d8cde531b62a89e76d9a5a: format document
3. a6841fca10314a453e37a9fed1d3a9f1947ca48a: add expected list of features to be considered otel compat
> Update otel spec to latest discussions

- src/docs/integrations/jira-server.mdx
Follow up to https://github.com/getsentry/sentry-docs/pull/5944
> fix(jira-server): Substitue jira_server for jira-server

- package.json
- yarn.lock
This is required since volta does not provide m1 builds of node 14
> build: Bump to node 16

- src/components/sidebar.tsx
- src/docs/frontend/upgrade-policies.mdx
Introduces a new section on dependency upgrade policies for the frontend
> feat(frontend): Add docs on upgrade policies

- src/docs/options.mdx
> Fix incorrect link to options management UI

- src/docs/sdk/event-payloads/index.mdx
> Fixed event size limit

- src/docs/sdk/features.mdx
is this in dev docs somewhere already?
> beforeSend clarification

- src/docs/sdk/performance/span-data-conventions.mdx
I made a mistake when initially adding this, amending!
> Update body/transfer size unit from string -> number

- src/docs/self-hosted/backup.mdx
closes https://github.com/getsentry/self-hosted/issues/1995
> Tweak self-hosted backup command

- src/docs/feature-flags.mdx
Helps folks self-serve, we sometimes field questions about what flags are available.
> Link to feature flag definitions

- src/components/sidebar.tsx
- src/docs/philosophy.mdx
Moves the document from gdocs to develop docs.
> Added developer philosophy document

- src/components/sidebar.tsx
- src/docs/sdk/index.mdx
- src/docs/sdk/sample-format.mdx
We defined a format to upload a profile. This is the document explaining how to build and format it.
> feat(profiling): Document the Sample format

- src/docs/analytics.mdx
Just a few small fixes I happened to see while reading.
> fix(analytics): Tiny grammar fixes

- src/docs/analytics.mdx
[WOR-2823](https://getsentry.atlassian.net/browse/WOR-2823)
> ref: Add volume warning to analytics doc

- src/docs/environment/index.mdx
This bit me when getting my setup going.
> fix(dev env docs): Add note about restarting devservices when enabling Relay

- src/docs/sdk/client-reports.mdx
Google User Reports and Client Reports come up
> disambiguate with user feedback

- package.json
- yarn.lock
> Update sharp dependency to fix building on arm64

- vercel.json
This PR should fix the most of these errors:
Also updating `report-uri` endpoint.
> CSP: add sources that are in use but reported as violations

- src/docs/sdk/check-ins.mdx
Fixes https://github.com/getsentry/sentry/issues/47260
> feat(crons): Add upsert details for SDK payloads

- src/components/sidebar.tsx
- src/docs/sdk/event-payloads/index.mdx
- src/docs/sdk/event-payloads/lockreason.mdx
- src/docs/sdk/event-payloads/threads.mdx
- src/docs/sdk/sessions.mdx
* Adds new `abnormal_mechanism` field to the SessionUpdate interface used for ANR rate calculation
* Adds new `held_locks` field to the Threads interface used for ANR frontend improvements
* Adds new `LockReason` interface
Closes #900
> feat(payloads): Add new 'abnormal_mechanism' and 'held_locks' properties to the protocol

- src/docs/ab-testing/index.mdx
Some of the referred codepaths don't exist anymore. Updating them to new ones
> Update amplitude documentation

- src/docs/sdk/philosophy.mdx
Let's never forget we are building a product not just a library
> SDK: Don’t forget the big picture

- src/docs/sdk/event-payloads/contexts.mdx
- For use in Python and PHP SDKs.
> dev(replays): update contexts to include the replay context

- src/docs/sdk/check-ins.mdx
See https://github.com/getsentry/sentry/issues/49664
> feat(crons): Update SDK docs for empty check-ins

- src/docs/dynamic-sampling/architecture.mdx
- src/docs/dynamic-sampling/fidelity-and-biases.mdx
Related to https://github.com/getsentry/sentry-docs/issues/7108
Closes https://github.com/getsentry/sentry-docs/issues/7123
> refactor(dynamic-sampling): rename uniform bias

- src/docs/sdk/features.mdx
Spec for https://docs.sentry.io/platforms/android/configuration/integrations/apollo3/#graphql-client-errors
> Document GraphQL client errors

- src/docs/sdk/data-handling.mdx
- src/docs/sdk/features.mdx
- src/docs/sdk/performance/span-data-conventions.mdx
https://www.notion.so/sentry/Update-Docs-for-URI-Fragments-65e8e6db3ad3467abb165d75118b103c
> Fragments are URI only - Browser SDKs

- src/docs/sdk/performance/trace-origin.mdx
Clarify that origin should rarely change.
> fix(trace-origin): Should rarely change

- src/docs/sdk/check-ins.mdx
Updating this page: https://develop.sentry.dev/sdk/check-ins/
> fix(check-ins): Remove duplicate words

- src/docs/frontend/network-requests.mdx
- Fixes some wrong type/variable names in the code example
- Adds a bit more explanation about what is in the code example
> fix(frontend): Better code example and explanation for network request mutation section

- src/docs/sdk/performance/span-operations.mdx
We might add more span OPs in the future.
> Add `ui.livewire`

- src/docs/sdk/performance/span-data-conventions.mdx
Based on https://github.com/getsentry/team-sdks/issues/19
> Add new database span data

- src/docs/environment/index.mdx
following https://github.com/getsentry/sentry/pull/54588
> devenv: update createuser stuff

- src/docs/frontend/development-server.mdx
> docs(dev-ui): Update paragraph about dev-ui, domains and cookies

- src/docs/testing.mdx
- kafka isn't in a special suite any more
- visual snapshots are gone
> remove some obsolete sections from testing.mdx

- src/docs/integrations/slack/index.mdx
> Add missing slash, to do like other examples

- src/docs/services/queue.mdx
Followup from INC-504 where we added an argument and rolling back was painful
> docs: Add note about adding celery arguments

- src/docs/sdk/performance/span-data-conventions.mdx
https://github.com/getsentry/rfcs/pull/75/files
> spans: add thread label and id to span data conventions

- src/docs/integrations/discord/index.mdx
Remove feature flag usage from developer docs after GA.
> ref(discord): Remove mentions of feature flags for Discord

- src/docs/workflow.mdx
the staging environment no longer exists
> remove mention of staging in workflow docs

- src/components/codeContext.tsx
The DSN loader has never worked in develop docs as develop.sentry.dev is not in the allowlist for CORS domains.
DSN substitution is infrequently used in develop docs and not having it is simpler than fixing and maintaining it.
> chore: Remove DSN loader from develop docs

- src/docs/integrations/msteams/index.mdx
Adding more instructions on how to approve custom MS Teams applications.
> fix: Update MS Teams installation instructions

- src/docs/sdk/performance/span-data-conventions.mdx
Add total, slow and frozen frames to span data conventions.
> feat: Add frames to span data conventions

- src/docs/sdk/check-ins.mdx
Add thresholds to config example
> docs(crons): Add thresholds to config example

- src/docs/sdk/performance/span-data-conventions.mdx
ref https://github.com/getsentry/team-sdks/issues/40
> Add code span data attributes

- src/docs/dynamic-sampling/fidelity-and-biases.mdx
> Fix dsc link

- src/docs/issue-platform.mdx
Fixes https://github.com/getsentry/sentry/issues/62507
> docs(issue-platform): Clarify documentation for StatusChangeMessage payloads

- src/docs/sdk/event-payloads/contexts.mdx
Closes https://github.com/getsentry/sentry-java/issues/1435
> Add new/missing context fields

- src/docs/sdk/performance/dynamic-sampling-context.mdx
See https://github.com/getsentry/sentry/issues/58767#issuecomment-1808116241
> Indicate that user segment is deprecated

- src/docs/frontend/index.mdx
> ref: remove prop types section

- src/docs/feature-flags/index.mdx
It should be `sentry.conf.py` right not `sentry.config.py`
> Fix feature flag local development file path

- src/docs/api/index.mdx
`Desiging` -> `Designing`
`Public API checklist` -> `Public API Checklist`
> nit(api): fix small typos on API page

- src/docs/sdk/hub_and_scope_refactoring.mdx
Trying to refine hubs/scopes merge docs.
I'll open a separate PR for POTEL changes.
> WIP hubs/scopes clarifications

- src/docs/self-hosted/troubleshooting.mdx
I feel this should be on the develop docs since I see so many people asking this question.
/cc @azaslavsky @hubertdeng123 @chadwhitacre
> docs(self-hosted): csrf troubleshooting

- src/docs/sdk/unified-api/index.mdx
With the work on hubs and scopes refactoring, this page needs a disclaimer even more than before 
https://develop.sentry.dev/sdk/hub_and_scope_refactoring/
> Unified API Disclaimer

- src/docs/sdk/metrics.mdx
Add the new replacement Regex and replacement map for tag values.
> Meric Normalization

- src/docs/sdk/metrics.mdx
Add a recommendation for the memory footprint of the aggregator for mobile SDKs.
> feat(metrics): Mobile aggregator memory footprint

- src/docs/sdk/metrics.mdx
Explain that \w could include unwanted chars.
> Metric Normalization note on w

- src/docs/integrations/discord/index.mdx
fixed a small typo in the documentation
> fixed typo

- src/docs/feature-flags/index.mdx
Add docs for the new way to use options based feature flags
> Add docs for options based feature flags

- src/docs/self-hosted/index.mdx
> Update index.mdx grammar

- src/docs/sdk/performance/modules/index.mdx
- src/docs/sdk/performance/modules/queue.mdx
https://develop-git-queue-module.sentry.dev/sdk/performance/modules/queue/
**Producer**
**Consumer**
> Queue Integration

- src/docs/sdk/performance/modules/requests.mdx
- src/docs/sdk/performance/span-data-conventions.mdx
> feat(perf): Add documentation for Requests instrumentation

- src/docs/architecture.mdx
Move these out of notion into an easier to find long-term home. More multiregion docs will be added as they are completed.
> feat: Add multiregion overview docs

- src/docs/database-migrations.mdx
- src/docs/environment/index.mdx
- Add docs on how to run siloed servers locally
- Add docs on maintaining split silo databases
> feat: Add silo mode local development server and migration docs

- src/docs/sdk/event-payloads/message.mdx
See also https://github.com/getsentry/relay/pull/3589
> ref(sdk): Update examples with canonical name for logentry

- src/docs/testing.mdx
Add docs on multi-region testing helpers
> feat(hybridcloud) Add documentation for testing helpers

- src/docs/sdk/performance/modules/index.mdx
- src/docs/sdk/performance/modules/queries.mdx
👋🏻 the Query Source stuff is an omission, but I can add that later both here, and on the page that describes the options the SDK should support.
> feat(insights): Add documentation for Queries module

- src/docs/sdk/performance/opentelemetry.mdx
> docs(opentelemetry): Fix typo

- src/docs/delightful-developer-metrics/ui.mdx
Closes https://github.com/getsentry/sentry/issues/71517
> Update DDM feature flags

- src/docs/feature-flags/flagpole.mdx
Adds developer information on Flagpole. Updates to the core Feature-Flags page will be in a follow-up PR.
> feat(flagpole): Adds core flagpole documentation

- src/docs/sdk/performance/span-operations.mdx
Added three missing categories, sorted the list of categories and formatted the doc.
> Added missing categories

- src/docs/integrations/github.mdx
Closes https://github.com/getsentry/sentry/issues/69837
> fix(github): troubleshooting guide for invalid application name

- src/docs/backend/cross-region-rpc.mdx
Paths have changed and docs need to be updated.
> chore(hybridcloud) Update hybridcloud examples to use new paths

- src/docs/analytics.mdx
> ref(analytics): Update amplitude analytics docs
